//go:build rtg

// Code generated by rtg; DO NOT EDIT.
// rtg:unit example.com/fixture/cmd/app
package main

// rtg:import "example.com/fixture/pkg/answer"
// rtg:ref example.com/fixture/pkg/answer Print => rtg_example_com_fixture_pkg_answer_Print

// rtg:decl func appMain => rtg_example_com_fixture_cmd_app_appMain cmd/app/main.go
func rtg_example_com_fixture_cmd_app_appMain() int {
	return rtg_example_com_fixture_pkg_answer_Print()
}

// rtg:decl func main => rtg_example_com_fixture_cmd_app_main cmd/app/main.go
func rtg_example_com_fixture_cmd_app_main() {
	rtg_example_com_fixture_cmd_app_appMain()
}
