//go:build rtg

// Code generated by rtg; DO NOT EDIT.
// rtg:unit example.com/fixture/pkg/answer
package answer

// rtg:export Print => rtg_example_com_fixture_pkg_answer_Print

// rtg:decl func Print => rtg_example_com_fixture_pkg_answer_Print pkg/answer/answer.go
func rtg_example_com_fixture_pkg_answer_Print() int {
	print("PASS\n")
	return 0
}
