// Code generated by rtgschemagen; DO NOT EDIT.
// schema-sha256: 3efdf2c4cd720f2d3c2e1967263092b19c1b22390bb358756961b5e94ba02133

package unit

const (
	Magic         = "RTGU"
	Version       = 1
	TagUnit       = 1
	TagPackage    = 2
	TagImportPath = 3
	TagText       = 7
	TagTokens     = 8
	TagDecls      = 9
	TagFuncs      = 10
	TagIndexes    = 11
	TagComps      = 12
	TagAssigns    = 13
	TagReturns    = 14
	TagCalls      = 15
	TagRefs       = 16
	TagSels       = 17
	TagTypes      = 18
	TagTypeRefs   = 19
	TagLocals     = 20
	TagSigs       = 21
	TagDeclMeta   = 22
	TagImports    = 23
	TagSymbols    = 24
	TagInitOrder  = 25
	TagConsts     = 26
	TagTypeFields = 27
	TagTypeIfaces = 28
	TagMethods    = 29
	TagTypeFuncs  = 30
	TagStmts      = 31
)

func schemaChildTagIndex(tag int) int {
	if tag >= TagPackage && tag <= TagImportPath {
		return tag - 2
	}
	if tag >= TagText && tag <= TagStmts {
		return tag - 5
	}
	return -1
}

const schemaRequiredChildMaskLow = 63
const schemaRequiredChildMaskHigh = 0
