// Code generated by rtgschemagen; DO NOT EDIT.
// schema-sha256: 3efdf2c4cd720f2d3c2e1967263092b19c1b22390bb358756961b5e94ba02133

package main

const (
	rtgUnitMagic         = "RTGU"
	rtgUnitVersion       = 1
	rtgUnitTagUnit       = 1
	rtgUnitTagPackage    = 2
	rtgUnitTagImportPath = 3
	rtgUnitTagText       = 7
	rtgUnitTagTokens     = 8
	rtgUnitTagDecls      = 9
	rtgUnitTagFuncs      = 10
	rtgUnitTagIndexes    = 11
	rtgUnitTagComps      = 12
	rtgUnitTagAssigns    = 13
	rtgUnitTagReturns    = 14
	rtgUnitTagCalls      = 15
	rtgUnitTagRefs       = 16
	rtgUnitTagSels       = 17
	rtgUnitTagTypes      = 18
	rtgUnitTagTypeRefs   = 19
	rtgUnitTagLocals     = 20
	rtgUnitTagSigs       = 21
	rtgUnitTagDeclMeta   = 22
	rtgUnitTagImports    = 23
	rtgUnitTagSymbols    = 24
	rtgUnitTagInitOrder  = 25
	rtgUnitTagConsts     = 26
	rtgUnitTagTypeFields = 27
	rtgUnitTagTypeIfaces = 28
	rtgUnitTagMethods    = 29
	rtgUnitTagTypeFuncs  = 30
	rtgUnitTagStmts      = 31
)

func rtgUnitChildTagIndex(tag int) int {
	if tag >= rtgUnitTagPackage && tag <= rtgUnitTagImportPath {
		return tag - 2
	}
	if tag >= rtgUnitTagText && tag <= rtgUnitTagStmts {
		return tag - 5
	}
	return -1
}

const rtgUnitRequiredChildMaskLow = 63
const rtgUnitRequiredChildMaskHigh = 0
