// Code generated by renvoschemagen; DO NOT EDIT.
// schema-sha256: d4de4f6161dd24e74c0dcf844a5880e8677ffd2f213c7cf195142aa3ee808618

package main

const (
	renvoUnitMagic         = "RNVO"
	renvoUnitVersion       = 1
	renvoUnitTagUnit       = 1
	renvoUnitTagPackage    = 2
	renvoUnitTagImportPath = 3
	renvoUnitTagText       = 7
	renvoUnitTagTokens     = 8
	renvoUnitTagDecls      = 9
	renvoUnitTagFuncs      = 10
	renvoUnitTagIndexes    = 11
	renvoUnitTagComps      = 12
	renvoUnitTagAssigns    = 13
	renvoUnitTagReturns    = 14
	renvoUnitTagCalls      = 15
	renvoUnitTagRefs       = 16
	renvoUnitTagSels       = 17
	renvoUnitTagTypes      = 18
	renvoUnitTagTypeRefs   = 19
	renvoUnitTagLocals     = 20
	renvoUnitTagSigs       = 21
	renvoUnitTagDeclMeta   = 22
	renvoUnitTagImports    = 23
	renvoUnitTagSymbols    = 24
	renvoUnitTagInitOrder  = 25
	renvoUnitTagConsts     = 26
	renvoUnitTagTypeFields = 27
	renvoUnitTagTypeIfaces = 28
	renvoUnitTagMethods    = 29
	renvoUnitTagTypeFuncs  = 30
	renvoUnitTagStmts      = 31
)

func renvoUnitChildTagIndex(tag int) int {
	if tag >= renvoUnitTagPackage && tag <= renvoUnitTagImportPath {
		return tag - 2
	}
	if tag >= renvoUnitTagText && tag <= renvoUnitTagStmts {
		return tag - 5
	}
	return -1
}

const renvoUnitRequiredChildMaskLow = 63
const renvoUnitRequiredChildMaskHigh = 0
