package emit

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"j5.nz/rtg/rtg/unit"
)

func TestSourceEmitsHostGoSafeUnit(t *testing.T) {
	u := unit.Unit{
		ImportPath: "example.com/app/pkg/answer",
		Package:    "answer",
		Imports:    []string{"example.com/app/pkg/dep"},
		Exports: []unit.Symbol{
			{ImportPath: "example.com/app/pkg/answer", Name: "Value", UnitName: "rtg_example_com_app_pkg_answer_Value"},
		},
		References: []unit.Symbol{
			{ImportPath: "example.com/app/pkg/dep", Name: "Other", UnitName: "rtg_example_com_app_pkg_dep_Other"},
		},
		Decls: []unit.Decl{
			{Path: "answer.go", Kind: "func", Name: "Value", UnitName: "rtg_example_com_app_pkg_answer_Value", Body: "func rtg_example_com_app_pkg_answer_Value() int { return 7 }\n"},
		},
	}
	src := string(Source(u))
	checks := []string{
		"//go:build rtg\n\n",
		"// Code generated by rtg; DO NOT EDIT.\n",
		"// rtg:unit example.com/app/pkg/answer\n",
		"package answer\n",
		"// rtg:import \"example.com/app/pkg/dep\"\n",
		"// rtg:export Value => rtg_example_com_app_pkg_answer_Value\n",
		"// rtg:ref example.com/app/pkg/dep Other => rtg_example_com_app_pkg_dep_Other\n",
		"// rtg:decl func Value => rtg_example_com_app_pkg_answer_Value answer.go\n",
		"func rtg_example_com_app_pkg_answer_Value() int { return 7 }\n",
	}
	for _, check := range checks {
		if !strings.Contains(src, check) {
			t.Fatalf("emitted source missing %q:\n%s", check, src)
		}
	}
}

func TestSourceEscapesImportMetadata(t *testing.T) {
	u := unit.Unit{
		ImportPath: "example.com/app/pkg/answer",
		Package:    "answer",
		Imports:    []string{"example.com/app/pkg/dep\\quoted\"line\nnext"},
	}
	src := Source(u)
	if !strings.Contains(string(src), `// rtg:import "example.com/app/pkg/dep\\quoted\"line\nnext"`+"\n") {
		t.Fatalf("emitted source did not escape import metadata:\n%s", string(src))
	}
	parsed, err := unit.ParseSource("escaped.rtg.go", src)
	if err != nil {
		t.Fatalf("ParseSource failed: %v", err)
	}
	if len(parsed.Imports) != 1 || parsed.Imports[0] != u.Imports[0] {
		t.Fatalf("parsed imports = %#v, want %#v", parsed.Imports, u.Imports)
	}
}

func TestSourceEscapesUnitMetadata(t *testing.T) {
	u := unit.Unit{
		ImportPath: "example.com/app path\\quoted\"line\nnext",
		Package:    "main",
	}
	src := Source(u)
	if !strings.Contains(string(src), `// rtg:unit "example.com/app path\\quoted\"line\nnext"`+"\n") {
		t.Fatalf("emitted source did not escape unit metadata:\n%s", string(src))
	}
	parsed, err := unit.ParseSource("escapedunit.rtg.go", src)
	if err != nil {
		t.Fatalf("ParseSource failed: %v", err)
	}
	if parsed.ImportPath != u.ImportPath {
		t.Fatalf("parsed import path = %q, want %q", parsed.ImportPath, u.ImportPath)
	}
}

func TestSourceEscapesDeclarationPathMetadata(t *testing.T) {
	u := unit.Unit{
		ImportPath: "example.com/app/pkg/answer",
		Package:    "answer",
		Decls: []unit.Decl{
			{Path: "pkg dir/answer.go", Kind: "const", Body: "const (\n\trtg_example_com_app_pkg_answer_Value = 7\n)\n"},
		},
	}
	src := Source(u)
	if !strings.Contains(string(src), `// rtg:decl const "pkg dir/answer.go"`+"\n") {
		t.Fatalf("emitted source did not escape declaration path:\n%s", string(src))
	}
	parsed, err := unit.ParseSource("declpath.rtg.go", src)
	if err != nil {
		t.Fatalf("ParseSource failed: %v", err)
	}
	if len(parsed.Decls) != 1 {
		t.Fatalf("parsed declarations = %#v", parsed.Decls)
	}
	if parsed.Decls[0].Name != "" || parsed.Decls[0].Path != u.Decls[0].Path {
		t.Fatalf("parsed declaration = %#v, want empty name and path %q", parsed.Decls[0], u.Decls[0].Path)
	}
}

func TestSourceEscapesReferenceMetadata(t *testing.T) {
	u := unit.Unit{
		ImportPath: "example.com/app/pkg/answer",
		Package:    "answer",
		References: []unit.Symbol{
			{ImportPath: "example.com/app/pkg/dep path\\quoted\"line\nnext", Name: "Other", UnitName: "rtg_example_com_app_pkg_dep_Other"},
		},
	}
	src := Source(u)
	if !strings.Contains(string(src), `// rtg:ref "example.com/app/pkg/dep path\\quoted\"line\nnext" Other => rtg_example_com_app_pkg_dep_Other`+"\n") {
		t.Fatalf("emitted source did not escape reference metadata:\n%s", string(src))
	}
	parsed, err := unit.ParseSource("ref.rtg.go", src)
	if err != nil {
		t.Fatalf("ParseSource failed: %v", err)
	}
	if len(parsed.References) != 1 || parsed.References[0].ImportPath != u.References[0].ImportPath {
		t.Fatalf("parsed references = %#v, want %#v", parsed.References, u.References)
	}
}

func TestSourceBuildTagIsIgnoredByHostGo(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte("module example.com/hostsafe\n"), 0644); err != nil {
		t.Fatalf("WriteFile go.mod failed: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "main.go"), []byte("package main\n\nfunc main() {}\n"), 0644); err != nil {
		t.Fatalf("WriteFile main.go failed: %v", err)
	}
	unit := unitWithInvalidHostGo()
	if err := os.WriteFile(filepath.Join(dir, "generated.rtg.go"), Source(unit), 0644); err != nil {
		t.Fatalf("WriteFile generated.rtg.go failed: %v", err)
	}
	cmd := exec.Command("go", "list", ".")
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("go list failed, generated unit was not ignored:\n%s", string(out))
	}
}

func TestFileNameIsStableHostSafeName(t *testing.T) {
	got := FileName("example.com/app/cmd/app")
	want := "example_com_app_cmd_app.rtg.go"
	if got != want {
		t.Fatalf("FileName = %q, want %q", got, want)
	}
}

func unitWithInvalidHostGo() unit.Unit {
	return unit.Unit{
		ImportPath: "example.com/hostsafe/generated",
		Package:    "main",
		Decls: []unit.Decl{
			{Path: "generated.go", Kind: "func", Name: "invalid", Body: "this is not valid host Go\n"},
		},
	}
}
