package emit

import (
	"bytes"
	"sort"

	"j5.nz/rtg/rtg/unit"
)

func Source(u unit.Unit) []byte {
	var out bytes.Buffer
	out.WriteString("//go:build rtg\n")
	out.WriteByte('\n')
	out.WriteString("// Code generated by rtg; DO NOT EDIT.\n")
	out.WriteString("// rtg:unit ")
	out.WriteString(u.ImportPath)
	out.WriteByte('\n')
	out.WriteString("package ")
	out.WriteString(u.Package)
	out.WriteString("\n\n")
	imports := append([]string(nil), u.Imports...)
	sort.Strings(imports)
	for _, imp := range imports {
		out.WriteString("// rtg:import ")
		out.WriteString(quote(imp))
		out.WriteByte('\n')
	}
	exports := append([]unit.Symbol(nil), u.Exports...)
	sort.Slice(exports, func(i int, j int) bool {
		if exports[i].Name == exports[j].Name {
			return exports[i].UnitName < exports[j].UnitName
		}
		return exports[i].Name < exports[j].Name
	})
	for _, sym := range exports {
		out.WriteString("// rtg:export ")
		out.WriteString(sym.Name)
		out.WriteString(" => ")
		out.WriteString(sym.UnitName)
		out.WriteByte('\n')
	}
	refs := append([]unit.Symbol(nil), u.References...)
	sort.Slice(refs, func(i int, j int) bool {
		if refs[i].ImportPath == refs[j].ImportPath {
			return refs[i].Name < refs[j].Name
		}
		return refs[i].ImportPath < refs[j].ImportPath
	})
	for _, sym := range refs {
		out.WriteString("// rtg:ref ")
		out.WriteString(sym.ImportPath)
		out.WriteByte(' ')
		out.WriteString(sym.Name)
		out.WriteString(" => ")
		out.WriteString(sym.UnitName)
		out.WriteByte('\n')
	}
	if len(imports) > 0 || len(exports) > 0 || len(refs) > 0 {
		out.WriteByte('\n')
	}
	for _, decl := range u.Decls {
		out.WriteString("// rtg:decl ")
		out.WriteString(decl.Kind)
		if decl.Name != "" {
			out.WriteByte(' ')
			out.WriteString(decl.Name)
		}
		if decl.UnitName != "" {
			out.WriteString(" => ")
			out.WriteString(decl.UnitName)
		}
		out.WriteString(" ")
		out.WriteString(decl.Path)
		out.WriteByte('\n')
		out.WriteString(decl.Body)
		if len(decl.Body) == 0 || decl.Body[len(decl.Body)-1] != '\n' {
			out.WriteByte('\n')
		}
		out.WriteByte('\n')
	}
	return out.Bytes()
}

func quote(s string) string {
	var out bytes.Buffer
	out.WriteByte('"')
	for i := 0; i < len(s); i++ {
		if s[i] == '"' || s[i] == '\\' {
			out.WriteByte('\\')
		}
		out.WriteByte(s[i])
	}
	out.WriteByte('"')
	return out.String()
}
