package emit

import (
	"bytes"
	"strconv"

	"j5.nz/rtg/rtg/unit"
)

func FileName(importPath string) string {
	if importPath == "" {
		return "unit.rtg.go"
	}
	out := make([]byte, 0, len(importPath)+7)
	for i := 0; i < len(importPath); i++ {
		c := importPath[i]
		if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') {
			out = append(out, c)
		} else {
			out = append(out, '_')
		}
	}
	out = append(out, ".rtg.go"...)
	return string(out)
}

func Source(u unit.Unit) []byte {
	var out bytes.Buffer
	out.WriteString("//go:build rtg\n")
	out.WriteByte('\n')
	out.WriteString("// Code generated by rtg; DO NOT EDIT.\n")
	out.WriteString("// rtg:unit ")
	out.WriteString(quoteIfNeeded(u.ImportPath))
	out.WriteByte('\n')
	out.WriteString("package ")
	out.WriteString(u.Package)
	out.WriteString("\n\n")
	imports := append([]string(nil), u.Imports...)
	sortStrings(imports)
	for _, imp := range imports {
		out.WriteString("// rtg:import ")
		out.WriteString(quote(imp))
		out.WriteByte('\n')
	}
	exports := append([]unit.Symbol(nil), u.Exports...)
	sortSymbolsByName(exports)
	for _, sym := range exports {
		out.WriteString("// rtg:export ")
		out.WriteString(sym.Name)
		out.WriteString(" => ")
		out.WriteString(sym.UnitName)
		out.WriteByte('\n')
	}
	refs := append([]unit.Symbol(nil), u.References...)
	sortSymbolsByImportPathName(refs)
	for _, sym := range refs {
		out.WriteString("// rtg:ref ")
		out.WriteString(quoteIfNeeded(sym.ImportPath))
		out.WriteByte(' ')
		out.WriteString(sym.Name)
		out.WriteString(" => ")
		out.WriteString(sym.UnitName)
		out.WriteByte('\n')
	}
	if len(imports) > 0 || len(exports) > 0 || len(refs) > 0 {
		out.WriteByte('\n')
	}
	for i, decl := range u.Decls {
		out.WriteString("// rtg:decl ")
		out.WriteString(decl.Kind)
		if decl.Name != "" {
			out.WriteByte(' ')
			out.WriteString(decl.Name)
		}
		if decl.UnitName != "" {
			out.WriteString(" => ")
			out.WriteString(decl.UnitName)
		}
		out.WriteString(" ")
		out.WriteString(quoteIfNeeded(decl.Path))
		out.WriteByte('\n')
		out.WriteString(decl.Body)
		if len(decl.Body) == 0 || decl.Body[len(decl.Body)-1] != '\n' {
			out.WriteByte('\n')
		}
		if i+1 < len(u.Decls) {
			out.WriteByte('\n')
		}
	}
	return out.Bytes()
}

func quote(s string) string {
	return strconv.Quote(s)
}

func quoteIfNeeded(s string) string {
	for i := 0; i < len(s); i++ {
		if s[i] == ' ' || s[i] == '\t' || s[i] == '\r' || s[i] == '\n' || s[i] == '"' || s[i] == '\\' {
			return quote(s)
		}
	}
	return s
}

func sortStrings(values []string) {
	for i := 1; i < len(values); i++ {
		value := values[i]
		j := i - 1
		for j >= 0 && values[j] > value {
			values[j+1] = values[j]
			j = j - 1
		}
		values[j+1] = value
	}
}

func sortSymbolsByName(symbols []unit.Symbol) {
	for i := 1; i < len(symbols); i++ {
		value := symbols[i]
		j := i - 1
		for j >= 0 && symbolAfterByName(symbols[j], value) {
			symbols[j+1] = symbols[j]
			j = j - 1
		}
		symbols[j+1] = value
	}
}

func symbolAfterByName(a unit.Symbol, b unit.Symbol) bool {
	if a.Name == b.Name {
		return a.UnitName > b.UnitName
	}
	return a.Name > b.Name
}

func sortSymbolsByImportPathName(symbols []unit.Symbol) {
	for i := 1; i < len(symbols); i++ {
		value := symbols[i]
		j := i - 1
		for j >= 0 && symbolAfterByImportPathName(symbols[j], value) {
			symbols[j+1] = symbols[j]
			j = j - 1
		}
		symbols[j+1] = value
	}
}

func symbolAfterByImportPathName(a unit.Symbol, b unit.Symbol) bool {
	if a.ImportPath == b.ImportPath {
		return a.Name > b.Name
	}
	return a.ImportPath > b.ImportPath
}
