package emit

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"j5.nz/rtg/rtg/unit"
)

func TestSourceEmitsHostGoSafeUnit(t *testing.T) {
	u := unit.Unit{
		ImportPath: "example.com/app/pkg/answer",
		Package:    "answer",
		Imports:    []string{"example.com/app/pkg/dep"},
		Exports: []unit.Symbol{
			{ImportPath: "example.com/app/pkg/answer", Name: "Value", UnitName: "rtg_example_com_app_pkg_answer_Value"},
		},
		References: []unit.Symbol{
			{ImportPath: "example.com/app/pkg/dep", Name: "Other", UnitName: "rtg_example_com_app_pkg_dep_Other"},
		},
		Decls: []unit.Decl{
			{Path: "answer.go", Kind: "func", Name: "Value", UnitName: "rtg_example_com_app_pkg_answer_Value", Body: "func rtg_example_com_app_pkg_answer_Value() int { return 7 }\n"},
		},
	}
	src := string(Source(u))
	checks := []string{
		"//go:build rtg\n\n",
		"// Code generated by rtg; DO NOT EDIT.\n",
		"// rtg:unit example.com/app/pkg/answer\n",
		"package answer\n",
		"// rtg:import \"example.com/app/pkg/dep\"\n",
		"// rtg:export Value => rtg_example_com_app_pkg_answer_Value\n",
		"// rtg:ref example.com/app/pkg/dep Other => rtg_example_com_app_pkg_dep_Other\n",
		"// rtg:decl func Value => rtg_example_com_app_pkg_answer_Value answer.go\n",
		"func rtg_example_com_app_pkg_answer_Value() int { return 7 }\n",
	}
	for _, check := range checks {
		if !strings.Contains(src, check) {
			t.Fatalf("emitted source missing %q:\n%s", check, src)
		}
	}
}

func TestSourceBuildTagIsIgnoredByHostGo(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte("module example.com/hostsafe\n"), 0644); err != nil {
		t.Fatalf("WriteFile go.mod failed: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "main.go"), []byte("package main\n\nfunc main() {}\n"), 0644); err != nil {
		t.Fatalf("WriteFile main.go failed: %v", err)
	}
	unit := unitWithInvalidHostGo()
	if err := os.WriteFile(filepath.Join(dir, "generated.rtg.go"), Source(unit), 0644); err != nil {
		t.Fatalf("WriteFile generated.rtg.go failed: %v", err)
	}
	cmd := exec.Command("go", "list", ".")
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("go list failed, generated unit was not ignored:\n%s", string(out))
	}
}

func TestFileNameIsStableHostSafeName(t *testing.T) {
	got := FileName("example.com/app/cmd/app")
	want := "example_com_app_cmd_app.rtg.go"
	if got != want {
		t.Fatalf("FileName = %q, want %q", got, want)
	}
}

func unitWithInvalidHostGo() unit.Unit {
	return unit.Unit{
		ImportPath: "example.com/hostsafe/generated",
		Package:    "main",
		Decls: []unit.Decl{
			{Path: "generated.go", Kind: "func", Name: "invalid", Body: "this is not valid host Go\n"},
		},
	}
}
