package emit

import (
	"bytes"
	"sort"
	"strconv"

	"j5.nz/rtg/rtg/unit"
)

func FileName(importPath string) string {
	if importPath == "" {
		return "unit.rtg.go"
	}
	out := make([]byte, 0, len(importPath)+7)
	for i := 0; i < len(importPath); i++ {
		c := importPath[i]
		if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') {
			out = append(out, c)
		} else {
			out = append(out, '_')
		}
	}
	out = append(out, ".rtg.go"...)
	return string(out)
}

func Source(u unit.Unit) []byte {
	var out bytes.Buffer
	out.WriteString("//go:build rtg\n")
	out.WriteByte('\n')
	out.WriteString("// Code generated by rtg; DO NOT EDIT.\n")
	out.WriteString("// rtg:unit ")
	out.WriteString(quoteIfNeeded(u.ImportPath))
	out.WriteByte('\n')
	out.WriteString("package ")
	out.WriteString(u.Package)
	out.WriteString("\n\n")
	imports := append([]string(nil), u.Imports...)
	sort.Strings(imports)
	for _, imp := range imports {
		out.WriteString("// rtg:import ")
		out.WriteString(quote(imp))
		out.WriteByte('\n')
	}
	exports := append([]unit.Symbol(nil), u.Exports...)
	sort.Slice(exports, func(i int, j int) bool {
		if exports[i].Name == exports[j].Name {
			return exports[i].UnitName < exports[j].UnitName
		}
		return exports[i].Name < exports[j].Name
	})
	for _, sym := range exports {
		out.WriteString("// rtg:export ")
		out.WriteString(sym.Name)
		out.WriteString(" => ")
		out.WriteString(sym.UnitName)
		out.WriteByte('\n')
	}
	refs := append([]unit.Symbol(nil), u.References...)
	sort.Slice(refs, func(i int, j int) bool {
		if refs[i].ImportPath == refs[j].ImportPath {
			return refs[i].Name < refs[j].Name
		}
		return refs[i].ImportPath < refs[j].ImportPath
	})
	for _, sym := range refs {
		out.WriteString("// rtg:ref ")
		out.WriteString(quoteIfNeeded(sym.ImportPath))
		out.WriteByte(' ')
		out.WriteString(sym.Name)
		out.WriteString(" => ")
		out.WriteString(sym.UnitName)
		out.WriteByte('\n')
	}
	if len(imports) > 0 || len(exports) > 0 || len(refs) > 0 {
		out.WriteByte('\n')
	}
	for i, decl := range u.Decls {
		out.WriteString("// rtg:decl ")
		out.WriteString(decl.Kind)
		if decl.Name != "" {
			out.WriteByte(' ')
			out.WriteString(decl.Name)
		}
		if decl.UnitName != "" {
			out.WriteString(" => ")
			out.WriteString(decl.UnitName)
		}
		out.WriteString(" ")
		out.WriteString(quoteIfNeeded(decl.Path))
		out.WriteByte('\n')
		out.WriteString(decl.Body)
		if len(decl.Body) == 0 || decl.Body[len(decl.Body)-1] != '\n' {
			out.WriteByte('\n')
		}
		if i+1 < len(u.Decls) {
			out.WriteByte('\n')
		}
	}
	return out.Bytes()
}

func quote(s string) string {
	return strconv.Quote(s)
}

func quoteIfNeeded(s string) string {
	for i := 0; i < len(s); i++ {
		if s[i] == ' ' || s[i] == '\t' || s[i] == '\r' || s[i] == '\n' || s[i] == '"' || s[i] == '\\' {
			return quote(s)
		}
	}
	return s
}
