// Code generated by rtgschemagen; DO NOT EDIT.
// schema-sha256: 3efdf2c4cd720f2d3c2e1967263092b19c1b22390bb358756961b5e94ba02133

package rtgunit

const (
	Magic         = "RTGU"
	Version       = 1
	TagUnit       = 1
	TagPackage    = 2
	TagImportPath = 3
	TagText       = 7
	TagTokens     = 8
	TagDecls      = 9
	TagFuncs      = 10
	TagIndexes    = 11
	TagComps      = 12
	TagAssigns    = 13
	TagReturns    = 14
	TagCalls      = 15
	TagRefs       = 16
	TagSels       = 17
	TagTypes      = 18
	TagTypeRefs   = 19
	TagLocals     = 20
	TagSigs       = 21
	TagDeclMeta   = 22
	TagImports    = 23
	TagSymbols    = 24
	TagInitOrder  = 25
	TagConsts     = 26
	TagTypeFields = 27
	TagTypeIfaces = 28
	TagMethods    = 29
	TagTypeFuncs  = 30
	TagStmts      = 31
)

func schemaChildTagIndex(tag int) int {
	if tag >= TagPackage && tag <= TagImportPath {
		return tag - 2
	}
	if tag >= TagText && tag <= TagStmts {
		return tag - 5
	}
	return -1
}

const schemaRequiredChildMaskLow = 63
const schemaRequiredChildMaskHigh = 0

type SchemaTag struct {
	Name     string
	Number   uint16
	Role     string
	Required bool
	Payload  string
	Record   string
}

type SchemaField struct {
	Name     string
	Encoding string
}

type SchemaRecord struct {
	Name   string
	Fields []SchemaField
}

var WireSchemaTags = []SchemaTag{
	{"Unit", 1, "root", true, "children", ""},
	{"Package", 2, "child", true, "bytes", ""},
	{"ImportPath", 3, "child", true, "bytes", ""},
	{"Text", 7, "child", true, "bytes", ""},
	{"Tokens", 8, "child", true, "counted", "Token"},
	{"Decls", 9, "child", true, "counted", "Decl"},
	{"Funcs", 10, "child", true, "counted", "Func"},
	{"Indexes", 11, "child", false, "counted", "IndexExpr"},
	{"Comps", 12, "child", false, "counted", "CompositeExpr"},
	{"Assigns", 13, "child", false, "counted", "Assignment"},
	{"Returns", 14, "child", false, "counted", "Return"},
	{"Calls", 15, "child", false, "counted", "Call"},
	{"Refs", 16, "child", false, "counted", "NameRef"},
	{"Sels", 17, "child", false, "counted", "Selector"},
	{"Types", 18, "child", false, "counted", "TypeInfo"},
	{"TypeRefs", 19, "child", false, "counted", "TypeRef"},
	{"Locals", 20, "child", false, "counted", "LocalDecl"},
	{"Sigs", 21, "child", false, "counted", "FuncSignature"},
	{"DeclMeta", 22, "child", false, "counted", "DeclMeta"},
	{"Imports", 23, "child", false, "counted", "Import"},
	{"Symbols", 24, "child", false, "counted", "Symbol"},
	{"InitOrder", 25, "child", false, "counted", "InitOrderEntry"},
	{"Consts", 26, "child", false, "counted", "ConstValue"},
	{"TypeFields", 27, "child", false, "counted", "TypeFields"},
	{"TypeIfaces", 28, "child", false, "counted", "TypeIface"},
	{"Methods", 29, "child", false, "counted", "MethodInfo"},
	{"TypeFuncs", 30, "child", false, "counted", "TypeFuncSig"},
	{"Stmts", 31, "child", false, "counted", "Statement"},
}
var WireSchemaRecords = []SchemaRecord{
	{Name: "Token", Fields: []SchemaField{
		{"kind", "uvarint"},
		{"start", "uvarint delta from previous start"},
		{"size", "uvarint"},
		{"line", "uvarint delta from previous line"},
	}},
	{Name: "Decl", Fields: []SchemaField{
		{"kind", "uvarint"},
		{"name", "byte span: start, length"},
		{"tokens", "token span: start, length"},
	}},
	{Name: "Func", Fields: []SchemaField{
		{"name", "byte span: start, length"},
		{"start_tok", "uvarint"},
		{"name_tok", "uvarint delta from start_tok"},
		{"receiver", "token span: start, length"},
		{"body", "token span: start, length"},
		{"end_tok", "uvarint delta from body end"},
	}},
	{Name: "ExprSpan", Fields: []SchemaField{
		{"tokens", "token span: start, length"},
	}},
	{Name: "Field", Fields: []SchemaField{
		{"name_tok", "nullable uvarint: value+1, zero means absent"},
		{"type", "token span: start, length"},
		{"variadic", "uvarint boolean"},
	}},
	{Name: "Import", Fields: []SchemaField{
		{"name", "length-prefixed bytes"},
		{"import_path", "length-prefixed bytes"},
		{"package", "nullable uvarint"},
		{"name_tok", "nullable uvarint"},
		{"path_tok", "uvarint"},
		{"flags", "uvarint bitset: dot=1, blank=2"},
	}},
	{Name: "Symbol", Fields: []SchemaField{
		{"name", "length-prefixed bytes"},
		{"kind", "uvarint"},
		{"package", "nullable uvarint"},
		{"token", "uvarint"},
		{"owner_kind", "uvarint"},
		{"owner_index", "uvarint"},
	}},
	{Name: "DeclMeta", Fields: []SchemaField{
		{"decl_index", "uvarint"},
		{"symbol", "nullable uvarint"},
		{"value_index", "uvarint"},
		{"alias", "uvarint boolean"},
		{"type", "nullable token span: start+1, length"},
		{"value", "nullable token span: start+1, length"},
		{"values", "counted ExprSpan"},
	}},
	{Name: "InitOrderEntry", Fields: []SchemaField{
		{"decl_index", "uvarint"},
	}},
	{Name: "ConstValue", Fields: []SchemaField{
		{"decl_index", "uvarint"},
		{"kind", "uvarint"},
		{"value", "kind union: zigzag integer, length-prefixed bytes, or uvarint boolean"},
	}},
	{Name: "FuncSignature", Fields: []SchemaField{
		{"func_index", "uvarint"},
		{"receiver", "counted Field"},
		{"params", "counted Field"},
		{"results", "counted Field"},
	}},
	{Name: "Statement", Fields: []SchemaField{
		{"func_index", "uvarint"},
		{"kind", "uvarint"},
		{"tokens", "token span: start, length"},
		{"expr", "nullable token span"},
		{"body", "nullable token span"},
		{"else", "nullable token span"},
	}},
	{Name: "TypeInfo", Fields: []SchemaField{
		{"kind", "uvarint"},
		{"name", "byte span: start, length"},
		{"decl", "uvarint"},
		{"symbol", "nullable uvarint"},
		{"alias", "uvarint boolean"},
		{"type", "nullable token span"},
		{"length", "nullable token span"},
		{"key", "nullable token span"},
		{"element", "nullable token span"},
	}},
	{Name: "TypeFields", Fields: []SchemaField{
		{"type_index", "uvarint"},
		{"fields", "counted Field"},
	}},
	{Name: "TypeIface", Fields: []SchemaField{
		{"type_index", "uvarint"},
		{"embeds", "counted token spans"},
		{"methods", "counted name_tok, params Field list, results Field list"},
	}},
	{Name: "TypeFuncSig", Fields: []SchemaField{
		{"type_index", "uvarint"},
		{"params", "counted Field"},
		{"results", "counted Field"},
	}},
	{Name: "MethodInfo", Fields: []SchemaField{
		{"name_tok", "uvarint"},
		{"type_index", "uvarint"},
		{"symbol", "uvarint"},
		{"func_index", "uvarint"},
		{"pointer", "uvarint boolean"},
	}},
	{Name: "TypeRef", Fields: []SchemaField{
		{"owner_kind", "uvarint"},
		{"owner_index", "uvarint"},
		{"kind", "uvarint"},
		{"token", "uvarint"},
		{"base_tok", "uvarint"},
		{"dot_tok", "uvarint"},
		{"package", "nullable uvarint"},
		{"symbol", "nullable uvarint"},
	}},
	{Name: "LocalDecl", Fields: []SchemaField{
		{"func_index", "uvarint"},
		{"kind", "uvarint"},
		{"name", "byte span: start, length"},
		{"token", "uvarint"},
		{"scope", "nullable uvarint"},
		{"value_index", "uvarint"},
		{"alias", "uvarint boolean"},
		{"type", "nullable token span"},
		{"value", "nullable token span"},
		{"values", "counted ExprSpan"},
	}},
	{Name: "IndexExpr", Fields: []SchemaField{
		{"owner_kind", "uvarint"},
		{"owner_index", "uvarint"},
		{"tokens", "token span"},
		{"base", "token span"},
		{"open_tok", "uvarint"},
		{"close_tok", "uvarint"},
		{"index", "token span"},
	}},
	{Name: "CompositeExpr", Fields: []SchemaField{
		{"owner_kind", "uvarint"},
		{"owner_index", "uvarint"},
		{"tokens", "token span"},
		{"type", "token span"},
		{"open_tok", "uvarint"},
		{"close_tok", "uvarint"},
		{"elements", "counted ExprSpan"},
	}},
	{Name: "Assignment", Fields: []SchemaField{
		{"func_index", "uvarint"},
		{"kind", "uvarint"},
		{"tokens", "token span"},
		{"op_tok", "uvarint"},
		{"left", "token span"},
		{"right", "token span"},
		{"targets", "counted ExprSpan"},
		{"values", "counted ExprSpan"},
	}},
	{Name: "Return", Fields: []SchemaField{
		{"func_index", "uvarint"},
		{"tokens", "token span"},
		{"values", "counted ExprSpan"},
	}},
	{Name: "Call", Fields: []SchemaField{
		{"owner_kind", "uvarint"},
		{"owner_index", "uvarint"},
		{"kind", "uvarint"},
		{"callee_tok", "uvarint"},
		{"base_tok", "uvarint"},
		{"dot_tok", "uvarint"},
		{"arguments", "token span"},
		{"args", "counted ExprSpan"},
	}},
	{Name: "NameRef", Fields: []SchemaField{
		{"owner_kind", "uvarint"},
		{"owner_index", "uvarint"},
		{"kind", "uvarint"},
		{"token", "uvarint"},
		{"index", "nullable uvarint"},
		{"package", "nullable uvarint"},
	}},
	{Name: "Selector", Fields: []SchemaField{
		{"owner_kind", "uvarint"},
		{"owner_index", "uvarint"},
		{"kind", "uvarint"},
		{"base_tok", "uvarint"},
		{"dot_tok", "uvarint"},
		{"name_tok", "uvarint"},
		{"base_kind", "uvarint"},
		{"base_index", "nullable uvarint"},
		{"base_package", "nullable uvarint"},
		{"package", "nullable uvarint"},
		{"symbol", "nullable uvarint"},
	}},
}
