//go:build rtg

// Code generated by rtg; DO NOT EDIT.
// rtg:unit example.com/structfixture/pkg/state
package state

// rtg:export Counter => rtg_example_com_structfixture_pkg_state_Counter
// rtg:export Score => rtg_example_com_structfixture_pkg_state_Score

// rtg:decl type Counter => rtg_example_com_structfixture_pkg_state_Counter pkg/state/model.go
type rtg_example_com_structfixture_pkg_state_Counter struct {
	value int
}

// rtg:decl const base => rtg_example_com_structfixture_pkg_state_base pkg/state/model.go
const rtg_example_com_structfixture_pkg_state_base = 40

// rtg:decl var current => rtg_example_com_structfixture_pkg_state_current pkg/state/model.go
var rtg_example_com_structfixture_pkg_state_current rtg_example_com_structfixture_pkg_state_Counter

// rtg:decl func add => rtg_example_com_structfixture_pkg_state_add pkg/state/score.go
func rtg_example_com_structfixture_pkg_state_add(v int) int {
	rtg_example_com_structfixture_pkg_state_current.value = rtg_example_com_structfixture_pkg_state_current.value + v
	return rtg_example_com_structfixture_pkg_state_current.value
}

// rtg:decl func Score => rtg_example_com_structfixture_pkg_state_Score pkg/state/score.go
func rtg_example_com_structfixture_pkg_state_Score() int {
	rtg_example_com_structfixture_pkg_state_current.value = rtg_example_com_structfixture_pkg_state_base
	return rtg_example_com_structfixture_pkg_state_add(2)
}
