//go:build rtg

// Code generated by rtg; DO NOT EDIT.
// rtg:unit example.com/structfixture/cmd/app
package main

// rtg:import "example.com/structfixture/pkg/state"
// rtg:ref example.com/structfixture/pkg/state Score => rtg_example_com_structfixture_pkg_state_Score

// rtg:decl func main => rtg_example_com_structfixture_cmd_app_main cmd/app/main.go
func rtg_example_com_structfixture_cmd_app_main() {
	if rtg_example_com_structfixture_pkg_state_Score() == 42 {
		print("PASS\n")
		return
	}
	print("FAIL\n")
}

// rtg:decl func appMain => rtg_example_com_structfixture_cmd_app_appMain rtg-entrypoint
func rtg_example_com_structfixture_cmd_app_appMain() int {
	rtg_example_com_structfixture_cmd_app_main()
	return 0
}
