package link

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"j5.nz/rtg/rtg/unit"
)

type Plan struct {
	Units []unit.Unit
}

func Build(units []unit.Unit) (Plan, error) {
	if err := validateUniqueUnits(units); err != nil {
		return Plan{}, err
	}
	exports := map[string]unit.Symbol{}
	for _, u := range units {
		for _, sym := range u.Exports {
			key := symbolKey(sym.ImportPath, sym.Name)
			if existing, ok := exports[key]; ok && existing.UnitName != sym.UnitName {
				return Plan{}, fmt.Errorf("duplicate export %s.%s", sym.ImportPath, sym.Name)
			}
			exports[key] = sym
		}
	}
	for _, u := range units {
		for _, ref := range u.References {
			export, ok := exports[symbolKey(ref.ImportPath, ref.Name)]
			if !ok {
				return Plan{}, fmt.Errorf("%s: unresolved reference %s.%s", u.ImportPath, ref.ImportPath, ref.Name)
			}
			if export.UnitName != ref.UnitName {
				return Plan{}, fmt.Errorf("%s: reference %s.%s resolved to %s, expected %s", u.ImportPath, ref.ImportPath, ref.Name, export.UnitName, ref.UnitName)
			}
		}
	}
	if err := validateEntrypoint(units); err != nil {
		return Plan{}, err
	}
	ordered := append([]unit.Unit(nil), units...)
	sort.Slice(ordered, func(i int, j int) bool {
		return ordered[i].ImportPath < ordered[j].ImportPath
	})
	return Plan{Units: ordered}, nil
}

func validateUniqueUnits(units []unit.Unit) error {
	seen := map[string]bool{}
	for _, u := range units {
		if seen[u.ImportPath] {
			return fmt.Errorf("duplicate unit: %s", u.ImportPath)
		}
		seen[u.ImportPath] = true
	}
	return nil
}

func validateEntrypoint(units []unit.Unit) error {
	var found []string
	for _, u := range units {
		if u.Package != "main" {
			continue
		}
		for _, decl := range u.Decls {
			if decl.Name == "appMain" && decl.UnitName != "" {
				found = append(found, u.ImportPath)
			}
		}
	}
	if len(found) == 0 {
		return fmt.Errorf("missing entrypoint: package main must declare appMain")
	}
	if len(found) > 1 {
		return fmt.Errorf("multiple entrypoints: %s", strings.Join(found, ", "))
	}
	return nil
}

func symbolKey(importPath string, name string) string {
	return importPath + "\x00" + name
}

func Source(plan Plan) []byte {
	var out bytes.Buffer
	out.WriteString("//go:build rtg\n\n")
	out.WriteString("// Code generated by rtg linker; DO NOT EDIT.\n")
	out.WriteString("package main\n\n")
	var wrapper string
	for _, u := range plan.Units {
		out.WriteString("// rtg:linked-unit ")
		out.WriteString(u.ImportPath)
		out.WriteByte('\n')
		for _, decl := range u.Decls {
			out.WriteString(decl.Body)
			if decl.Body == "" || decl.Body[len(decl.Body)-1] != '\n' {
				out.WriteByte('\n')
			}
			out.WriteByte('\n')
			if wrapper == "" && u.Package == "main" && decl.Name == "appMain" && decl.UnitName != "" {
				wrapper = appMainWrapper(decl)
			}
		}
	}
	if wrapper != "" {
		out.WriteString(wrapper)
	}
	return out.Bytes()
}

func appMainWrapper(decl unit.Decl) string {
	prefix := "func " + decl.UnitName
	if !strings.HasPrefix(decl.Body, prefix) {
		return ""
	}
	brace := strings.Index(decl.Body, "{")
	if brace < 0 {
		return ""
	}
	signature := strings.TrimSpace(decl.Body[len(prefix):brace])
	if !strings.HasPrefix(signature, "(") {
		return ""
	}
	close := matchingParen(signature)
	if close < 0 {
		return ""
	}
	params := signature[:close+1]
	result := strings.TrimSpace(signature[close+1:])
	args := argumentNames(params)
	var out bytes.Buffer
	out.WriteString("func appMain")
	out.WriteString(signature)
	out.WriteString(" {\n")
	out.WriteByte('\t')
	if result != "" {
		out.WriteString("return ")
	}
	out.WriteString(decl.UnitName)
	out.WriteByte('(')
	out.WriteString(args)
	out.WriteString(")\n")
	out.WriteString("}\n")
	return out.String()
}

func matchingParen(s string) int {
	depth := 0
	for i := 0; i < len(s); i++ {
		if s[i] == '(' {
			depth++
		} else if s[i] == ')' {
			depth--
			if depth == 0 {
				return i
			}
		}
	}
	return -1
}

func argumentNames(params string) string {
	if len(params) < 2 {
		return ""
	}
	inner := strings.TrimSpace(params[1 : len(params)-1])
	if inner == "" {
		return ""
	}
	parts := strings.Split(inner, ",")
	var names []string
	for _, part := range parts {
		fields := strings.Fields(strings.TrimSpace(part))
		if len(fields) > 1 {
			names = append(names, fields[0])
		}
	}
	return strings.Join(names, ", ")
}
