package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

type bundleEntry struct {
	name  string
	isDir bool
}

type bundleFile struct {
	path string
	data []byte
}

func main() {
	root := flag.String("root", "rtg/std", "standard library source root")
	output := flag.String("output", "rtg/internal/driver/std_bundle_generated.go", "generated Go output")
	flag.Parse()

	files, dirs, err := collect(*root)
	if err != nil {
		fmt.Fprintln(os.Stderr, "rtgstdgen:", err)
		os.Exit(1)
	}
	data, err := generateSource(files, dirs)
	if err != nil {
		fmt.Fprintln(os.Stderr, "rtgstdgen:", err)
		os.Exit(1)
	}
	if err := os.WriteFile(*output, data, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "rtgstdgen:", err)
		os.Exit(1)
	}
}

func generateSource(files []bundleFile, dirs map[string][]bundleEntry) ([]byte, error) {
	return format.Source(generate(files, dirs))
}

func collect(root string) ([]bundleFile, map[string][]bundleEntry, error) {
	var files []bundleFile
	dirs := make(map[string][]bundleEntry)
	dirs["/std"] = nil
	err := filepath.WalkDir(root, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			return nil
		}
		name := entry.Name()
		if !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			return nil
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		rel = filepath.ToSlash(rel)
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if hostOnlySource(data) {
			return nil
		}
		bundlePath := "/std/" + rel
		files = append(files, bundleFile{path: bundlePath, data: data})
		addPathEntries(dirs, rel)
		return nil
	})
	if err != nil {
		return nil, nil, err
	}
	sort.Slice(files, func(i int, j int) bool { return files[i].path < files[j].path })
	for dir := range dirs {
		entries := dirs[dir]
		sort.Slice(entries, func(i int, j int) bool { return entries[i].name < entries[j].name })
		dirs[dir] = entries
	}
	return files, dirs, nil
}

func hostOnlySource(data []byte) bool {
	line := data
	if end := bytes.IndexByte(line, '\n'); end >= 0 {
		line = line[:end]
	}
	return string(bytes.TrimSpace(line)) == "//go:build !rtg"
}

func addPathEntries(dirs map[string][]bundleEntry, rel string) {
	parts := strings.Split(rel, "/")
	dir := "/std"
	for i := 0; i < len(parts)-1; i++ {
		addEntry(dirs, dir, bundleEntry{name: parts[i], isDir: true})
		dir += "/" + parts[i]
		if _, ok := dirs[dir]; !ok {
			dirs[dir] = nil
		}
	}
	addEntry(dirs, dir, bundleEntry{name: parts[len(parts)-1]})
}

func addEntry(dirs map[string][]bundleEntry, dir string, entry bundleEntry) {
	entries := dirs[dir]
	for i := 0; i < len(entries); i++ {
		if entries[i] == entry {
			return
		}
	}
	dirs[dir] = append(entries, entry)
}

func generate(files []bundleFile, dirs map[string][]bundleEntry) []byte {
	var out bytes.Buffer
	out.WriteString("// Code generated by rtgstdgen; DO NOT EDIT.\n")
	out.WriteString("//go:build rtg_bundle\n\n")
	out.WriteString("package driver\n\n")
	out.WriteString("const rtgBundledStdEnabled = true\n\n")
	out.WriteString("func bundledStdReadFile(path string) ([]byte, bool) {\n")
	for _, file := range files {
		fmt.Fprintf(&out, "\tif path == %s {\n\t\treturn []byte(%s), true\n\t}\n", strconv.Quote(file.path), strconv.Quote(string(file.data)))
	}
	out.WriteString("\treturn nil, false\n}\n\n")
	out.WriteString("func bundledStdReadDir(path string) ([]DirEntry, bool) {\n")
	dirNames := make([]string, 0, len(dirs))
	for dir := range dirs {
		dirNames = append(dirNames, dir)
	}
	sort.Strings(dirNames)
	for _, dir := range dirNames {
		fmt.Fprintf(&out, "\tif path == %s {\n", strconv.Quote(dir))
		out.WriteString("\t\treturn []DirEntry{")
		for _, entry := range dirs[dir] {
			fmt.Fprintf(&out, "{Name: %s, IsDir: %t},", strconv.Quote(entry.name), entry.isDir)
		}
		out.WriteString("}, true\n\t}\n")
	}
	out.WriteString("\treturn nil, false\n}\n")
	return out.Bytes()
}
