// Code generated by the future RTG Forms designer; DO NOT EDIT.

package main

import (
	"j5.nz/rtg/rtg/ide"
	"j5.nz/rtg/rtg/std/graphics"
)

func (f *MainForm) initializeComponent(root string) {
	f.Form.Initialize(1000, 700)
	uiFont := ide.NewUIFont()

	f.explorer = ide.NewExplorerControl(ide.OpenExplorer(root))
	f.explorer.SetBounds(rect(0, 0, 260, 700))
	f.explorer.SetFont(uiFont)
	f.explorer.OpenFile = f.explorerOpenFile

	f.editor = ide.NewEditorControl(ide.NewDocument(nil))
	f.editor.SetBounds(rect(260, 0, 740, 700))
	f.editor.SetFont(uiFont)
	f.editor.Save = f.saveCurrentFile

	f.Resize = f.formResize
	f.Add(&f.explorer.Control)
	f.Add(&f.editor.Control)
}

func rect(x, y, width, height int) graphics.Rect {
	return graphics.R(graphics.Scalar(x), graphics.Scalar(y), graphics.Scalar(width), graphics.Scalar(height))
}
