// Code generated by the future RTG Forms designer; DO NOT EDIT.

package main

import (
	"j5.nz/rtg/rtg/ide"
	"j5.nz/rtg/rtg/std/graphics"
)

func (f *MainForm) initializeComponent(root string) {
	f.Form.Initialize(1440, 520)
	uiFont := ide.NewInterfaceFont()
	codeFont := ide.NewUIFont()

	f.appBar = newWorkspaceAppBar(uiFont)
	f.appBar.SetTarget(f.selectedTarget)
	f.appBar.OpenTargets = f.toggleTargetMenu
	f.targetMenu = newWorkspaceTargetMenu(uiFont, workspaceTargets())
	f.targetMenu.Select = f.selectBuildTarget
	f.explorerFrame = newWorkspaceExplorerFrame(uiFont)
	f.editorFrame = newWorkspaceEditorFrame(uiFont)
	f.designer = newWorkspaceDesigner(uiFont)
	f.inspector = newWorkspaceInspector(uiFont)
	f.output = newWorkspaceOutput(uiFont)
	f.appBar.Build = f.buildProject
	f.appBar.Run = f.runProject
	f.editorFrame.ShowDesigner = f.showDesigner
	f.designer.ShowCode = f.showCode
	f.designer.SetDesign(&f.design)
	f.designer.Changed = f.designerChanged
	f.designer.SelectionChanged = f.designerSelectionChanged
	f.designer.AddControl = f.addDesignerControl
	f.designer.DeleteSelection = f.deleteDesignerControl
	f.inspector.SetDesign(&f.design)
	f.inspector.Changed = f.designerChanged
	f.inspector.CreateEvent = f.createDesignerEvent

	f.explorer = ide.NewExplorerControl(ide.OpenExplorer(root))
	f.explorer.SetFont(uiFont)
	f.explorer.OpenFile = f.explorerOpenFile

	f.editor = ide.NewEditorControl(ide.NewDocument(nil))
	f.editor.SetFont(codeFont)
	f.editor.Save = f.saveCurrentFile
	f.editor.Changed = f.editorChanged
	f.editor.Complete = f.completeEditor
	f.editor.Signature = f.signatureEditor

	f.Resize = f.formResize
	f.Add(&f.appBar.Control)
	f.Add(&f.explorerFrame.Control)
	f.Add(&f.editorFrame.Control)
	f.Add(&f.designer.Control)
	f.Add(&f.inspector.Control)
	f.Add(&f.output.Control)
	f.Add(&f.explorer.Control)
	f.Add(&f.editor.Control)
	f.Add(&f.targetMenu.Control)
	f.designer.SetVisible(false)
	f.inspector.SetVisible(false)
	f.targetMenu.SetVisible(false)
	f.formResize()
}

func rect(x, y, width, height int) graphics.Rect {
	return graphics.R(graphics.Scalar(x), graphics.Scalar(y), graphics.Scalar(width), graphics.Scalar(height))
}
