package unit

import (
	"strings"
	"testing"
)

func TestParseSourceRoundTripMetadata(t *testing.T) {
	u := Unit{
		ImportPath: "example.com/app/main",
		Package:    "main",
		Imports:    []string{"example.com/app/pkg/answer"},
		Exports:    []Symbol{{ImportPath: "example.com/app/main", Name: "Main", UnitName: "rtg_example_com_app_main_Main"}},
		References: []Symbol{{ImportPath: "example.com/app/pkg/answer", Name: "Value", UnitName: "rtg_example_com_app_pkg_answer_Value"}},
		Decls:      []Decl{{Kind: "func", Name: "Main", UnitName: "rtg_example_com_app_main_Main", Path: "main.go", Body: "func rtg_example_com_app_main_Main() int { return 0 }\n"}},
	}
	src := sourceForTest(u)
	parsed, err := ParseSource("main.rtg.go", src)
	if err != nil {
		t.Fatalf("ParseSource failed: %v", err)
	}
	if parsed.ImportPath != u.ImportPath || parsed.Package != u.Package {
		t.Fatalf("parsed identity = %#v", parsed)
	}
	if len(parsed.Imports) != 1 || parsed.Imports[0] != "example.com/app/pkg/answer" {
		t.Fatalf("imports = %#v", parsed.Imports)
	}
	if len(parsed.Exports) != 1 || parsed.Exports[0].UnitName != "rtg_example_com_app_main_Main" {
		t.Fatalf("exports = %#v", parsed.Exports)
	}
	if len(parsed.References) != 1 || parsed.References[0].ImportPath != "example.com/app/pkg/answer" {
		t.Fatalf("references = %#v", parsed.References)
	}
	if len(parsed.Decls) != 1 || parsed.Decls[0].Name != "Main" {
		t.Fatalf("decls = %#v", parsed.Decls)
	}
	if !strings.Contains(parsed.Decls[0].Body, "func rtg_example_com_app_main_Main() int") {
		t.Fatalf("decl body was not preserved: %q", parsed.Decls[0].Body)
	}
}

func sourceForTest(u Unit) []byte {
	var b strings.Builder
	b.WriteString("//go:build rtg\n\n")
	b.WriteString("// Code generated by rtg; DO NOT EDIT.\n")
	b.WriteString("// rtg:unit ")
	b.WriteString(u.ImportPath)
	b.WriteString("\npackage ")
	b.WriteString(u.Package)
	b.WriteString("\n\n")
	for _, imp := range u.Imports {
		b.WriteString("// rtg:import \"")
		b.WriteString(imp)
		b.WriteString("\"\n")
	}
	for _, sym := range u.Exports {
		b.WriteString("// rtg:export ")
		b.WriteString(sym.Name)
		b.WriteString(" => ")
		b.WriteString(sym.UnitName)
		b.WriteByte('\n')
	}
	for _, sym := range u.References {
		b.WriteString("// rtg:ref ")
		b.WriteString(sym.ImportPath)
		b.WriteByte(' ')
		b.WriteString(sym.Name)
		b.WriteString(" => ")
		b.WriteString(sym.UnitName)
		b.WriteByte('\n')
	}
	for _, decl := range u.Decls {
		b.WriteString("// rtg:decl ")
		b.WriteString(decl.Kind)
		b.WriteByte(' ')
		b.WriteString(decl.Name)
		b.WriteString(" => ")
		b.WriteString(decl.UnitName)
		b.WriteByte(' ')
		b.WriteString(decl.Path)
		b.WriteByte('\n')
		b.WriteString(decl.Body)
	}
	return []byte(b.String())
}
