// Code generated by renvoresultgen from protocol.json. DO NOT EDIT.
package resultabi

type State uint32

const (
	Magic                    uint32 = 0x52564e52
	Version                  uint16 = 1
	Size                            = 64
	SymbolName                      = "renvores"
	SectionName                     = ".renvo.result"
	OffsetMagic                     = 0
	FieldSizeMagic                  = 4
	OffsetVersion                   = 4
	FieldSizeVersion                = 2
	OffsetSize                      = 6
	FieldSizeSize                   = 2
	OffsetProfile                   = 8
	FieldSizeProfile                = 4
	OffsetState                     = 12
	FieldSizeState                  = 4
	OffsetCurrentProbe              = 16
	FieldSizeCurrentProbe           = 4
	OffsetFailureProbe              = 20
	FieldSizeFailureProbe           = 4
	OffsetCompletedProbes           = 24
	FieldSizeCompletedProbes        = 4
	OffsetFlags                     = 28
	FieldSizeFlags                  = 4
	OffsetExpected                  = 32
	FieldSizeExpected               = 8
	OffsetObserved                  = 40
	FieldSizeObserved               = 8
	OffsetSignature                 = 48
	FieldSizeSignature              = 8
	OffsetSequence                  = 56
	FieldSizeSequence               = 4
	OffsetReserved                  = 60
	FieldSizeReserved               = 4
)

const (
	StateNotStarted       State = 0
	StateRunning          State = 1
	StatePassed           State = 2
	StateFailedComparison State = 3
	StateTrapReset        State = 4
	StateProfileMismatch  State = 5
)
