package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRunEmitUnit(t *testing.T) {
	root := t.TempDir()
	writeCLIFile(t, root, "go.mod", "module example.com/app\n")
	writeCLIFile(t, root, "cmd/app/main.go", `package main

func appMain() int {
	return 0
}
`)
	out := filepath.Join(root, "out.rtg.go")
	cfg := config{output: out, emitUnit: true, inputs: []string{filepath.Join(root, "cmd", "app")}}
	if err := run(cfg); err != nil {
		t.Fatalf("run failed: %v", err)
	}
	data, err := os.ReadFile(out)
	if err != nil {
		t.Fatalf("ReadFile failed: %v", err)
	}
	src := string(data)
	if !strings.Contains(src, "//go:build rtg\n") {
		t.Fatalf("emitted unit missing build tag:\n%s", src)
	}
	if !strings.Contains(src, "// rtg:unit example.com/app/cmd/app\n") {
		t.Fatalf("emitted unit missing import path:\n%s", src)
	}
	if strings.Contains(src, "import ") {
		t.Fatalf("emitted unit retained import declaration:\n%s", src)
	}
	if !strings.Contains(src, "// rtg:decl func appMain => rtg_example_com_app_cmd_app_appMain ") {
		t.Fatalf("emitted unit missing parsed declaration marker:\n%s", src)
	}
	if !strings.Contains(src, "func rtg_example_com_app_cmd_app_appMain() int") {
		t.Fatalf("emitted unit did not rewrite appMain symbol:\n%s", src)
	}
}

func TestRunEmitUnitRewritesLoadedPackageSelector(t *testing.T) {
	root := t.TempDir()
	writeCLIFile(t, root, "go.mod", "module example.com/app\n")
	writeCLIFile(t, root, "cmd/app/main.go", `package main

import "example.com/app/pkg/answer"

func appMain() int {
	return answer.Value()
}
`)
	writeCLIFile(t, root, "pkg/answer/answer.go", `package answer

func Value() int {
	return 7
}
`)
	out := filepath.Join(root, "out.rtg.go")
	cfg := config{output: out, emitUnit: true, inputs: []string{filepath.Join(root, "cmd", "app")}}
	if err := run(cfg); err != nil {
		t.Fatalf("run failed: %v", err)
	}
	data, err := os.ReadFile(out)
	if err != nil {
		t.Fatalf("ReadFile failed: %v", err)
	}
	src := string(data)
	if !strings.Contains(src, "// rtg:ref example.com/app/pkg/answer Value => rtg_example_com_app_pkg_answer_Value\n") {
		t.Fatalf("emitted unit missing reference:\n%s", src)
	}
	if !strings.Contains(src, "return rtg_example_com_app_pkg_answer_Value()") {
		t.Fatalf("emitted unit did not rewrite imported selector:\n%s", src)
	}
}

func TestRunCheckRejectsExcludedFeature(t *testing.T) {
	root := t.TempDir()
	writeCLIFile(t, root, "go.mod", "module example.com/app\n")
	writeCLIFile(t, root, "cmd/app/main.go", `package main

func appMain() int {
	ch := make(chan int)
	go func() { ch <- 1 }()
	return <-ch
}
`)
	cfg := config{check: true, inputs: []string{filepath.Join(root, "cmd", "app")}}
	err := run(cfg)
	if err == nil {
		t.Fatalf("run check succeeded for excluded features")
	}
	msg := err.Error()
	for _, want := range []string{"channels are not supported", "goroutines are not supported"} {
		if !strings.Contains(msg, want) {
			t.Fatalf("error %q missing %q", msg, want)
		}
	}
}

func TestRunCheckAcceptsSimplePackage(t *testing.T) {
	root := t.TempDir()
	writeCLIFile(t, root, "go.mod", "module example.com/app\n")
	writeCLIFile(t, root, "cmd/app/main.go", `package main

func appMain() int {
	return 0
}
`)
	cfg := config{check: true, inputs: []string{filepath.Join(root, "cmd", "app")}}
	if err := run(cfg); err != nil {
		t.Fatalf("run check failed: %v", err)
	}
}

func TestRunLinkValidatesUnitReferences(t *testing.T) {
	root := t.TempDir()
	mainUnit := filepath.Join(root, "main.rtg.go")
	depUnit := filepath.Join(root, "dep.rtg.go")
	out := filepath.Join(root, "link.txt")
	writeCLIFile(t, root, "main.rtg.go", `//go:build rtg

// Code generated by rtg; DO NOT EDIT.
// rtg:unit example.com/app/main
package main

// rtg:ref example.com/app/dep Value => rtg_example_com_app_dep_Value
// rtg:decl func appMain => rtg_example_com_app_main_appMain main.go
func rtg_example_com_app_main_appMain() int { return rtg_example_com_app_dep_Value() }
`)
	writeCLIFile(t, root, "dep.rtg.go", `//go:build rtg

// Code generated by rtg; DO NOT EDIT.
// rtg:unit example.com/app/dep
package dep

// rtg:export Value => rtg_example_com_app_dep_Value
// rtg:decl func Value => rtg_example_com_app_dep_Value dep.go
func rtg_example_com_app_dep_Value() int { return 7 }
`)
	cfg := config{link: true, output: out, inputs: []string{mainUnit, depUnit}}
	if err := run(cfg); err != nil {
		t.Fatalf("run link failed: %v", err)
	}
	data, err := os.ReadFile(out)
	if err != nil {
		t.Fatalf("ReadFile failed: %v", err)
	}
	got := string(data)
	for _, want := range []string{
		"package main\n",
		"func rtg_example_com_app_dep_Value() int { return 7 }\n",
		"func rtg_example_com_app_main_appMain() int { return rtg_example_com_app_dep_Value() }\n",
		"func appMain() int {\n\treturn rtg_example_com_app_main_appMain()\n}\n",
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("linked source missing %q:\n%s", want, got)
		}
	}
}

func TestRunLinkRejectsMissingExport(t *testing.T) {
	root := t.TempDir()
	mainUnit := filepath.Join(root, "main.rtg.go")
	out := filepath.Join(root, "link.txt")
	writeCLIFile(t, root, "main.rtg.go", `//go:build rtg

// Code generated by rtg; DO NOT EDIT.
// rtg:unit example.com/app/main
package main

// rtg:ref example.com/app/dep Value => rtg_example_com_app_dep_Value
`)
	cfg := config{link: true, output: out, inputs: []string{mainUnit}}
	err := run(cfg)
	if err == nil {
		t.Fatalf("run link succeeded with missing export")
	}
	if !strings.Contains(err.Error(), "unresolved reference") {
		t.Fatalf("error = %q", err)
	}
}

func writeCLIFile(t *testing.T, root string, name string, data string) {
	t.Helper()
	path := filepath.Join(root, name)
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		t.Fatalf("MkdirAll failed: %v", err)
	}
	if err := os.WriteFile(path, []byte(data), 0644); err != nil {
		t.Fatalf("WriteFile failed: %v", err)
	}
}
