// Code generated by the future RENVO Forms designer; DO NOT EDIT.

package main

import (
	"renvo.dev/forms"
	"renvo.dev/ide"
	"renvo.dev/std/graphics"
)

func (f *MainForm) initializeComponent(root string) {
	f.Form.Initialize(1440, 520)
	uiFont := ide.NewInterfaceFont()
	codeFont := ide.NewUIFont()

	f.appBar = newWorkspaceAppBar(uiFont)
	f.appBar.SetAccessibilityID("app-bar")
	f.appBar.SetTarget(f.selectedTarget)
	f.appBar.OpenTargets = f.toggleTargetMenu
	f.targetMenu = newWorkspaceTargetMenu(uiFont, workspaceTargets())
	f.targetMenu.SetAccessibilityID("target-menu")
	f.targetMenu.Select = f.selectBuildTarget
	f.explorerFrame = newWorkspaceExplorerFrame(uiFont)
	f.explorerFrame.SetAccessibilityID("explorer-pane")
	f.editorFrame = newWorkspaceEditorFrame(uiFont)
	f.editorFrame.SetAccessibilityID("editor-pane")
	f.designer = newWorkspaceDesigner(uiFont)
	f.designer.SetAccessibilityID("form-designer")
	f.designer.SetAccessibilityName("Form designer")
	f.inspector = newWorkspaceInspector(uiFont)
	f.inspector.SetAccessibilityID("properties")
	f.inspector.SetAccessibilityName("Properties")
	f.output = newWorkspaceOutput(uiFont)
	f.output.SetAccessibilityID("build-output")
	f.appBar.Build = f.buildProject
	f.appBar.Run = f.runProject
	f.menuBar = forms.NewMenuBar()
	f.menuBar.SetAccessibilityID("main-menu")
	f.menuBar.SetFont(uiFont)
	f.menuBar.SetBounds(rect(0, 0, 168, 28))
	f.menuBar.SetDock(forms.DockTop)
	fileMenu := forms.NewMenu("File")
	newProjectItem := forms.NewMenuItem("New Project...")
	newProjectItem.SetShortcut(forms.Shortcut{Key: graphics.KeyN, Modifiers: graphics.ModifierShift, Primary: true, Text: "Ctrl/Cmd+Shift+N"})
	newProjectItem.Activate = f.chooseNewProject
	fileMenu.Add(newProjectItem)
	openProjectItem := forms.NewMenuItem("Open Project...")
	openProjectItem.SetShortcut(forms.Shortcut{Key: graphics.KeyO, Modifiers: graphics.ModifierShift, Primary: true, Text: "Ctrl/Cmd+Shift+O"})
	openProjectItem.Activate = f.chooseOpenProject
	fileMenu.Add(openProjectItem)
	fileMenu.Add(forms.NewMenuSeparator())
	openFileItem := forms.NewMenuItem("Open File...")
	openFileItem.SetShortcut(forms.Shortcut{Key: graphics.KeyO, Primary: true, Text: "Ctrl/Cmd+O"})
	openFileItem.Activate = f.chooseOpenFile
	fileMenu.Add(openFileItem)
	saveItem := forms.NewMenuItem("Save")
	saveItem.SetShortcut(forms.Shortcut{Key: graphics.KeyS, Primary: true, Text: "Ctrl/Cmd+S"})
	saveItem.Activate = f.saveCurrentFile
	fileMenu.Add(saveItem)
	saveAsItem := forms.NewMenuItem("Save As...")
	saveAsItem.SetShortcut(forms.Shortcut{Key: graphics.KeyS, Modifiers: graphics.ModifierShift, Primary: true, Text: "Ctrl/Cmd+Shift+S"})
	saveAsItem.Activate = f.saveCurrentFileAs
	fileMenu.Add(saveAsItem)
	f.menuBar.Add(fileMenu)
	buildMenu := forms.NewMenu("Build")
	buildItem := forms.NewMenuItem("Build Project")
	buildItem.SetShortcut(forms.Shortcut{Key: graphics.KeyB, Primary: true, Text: "Ctrl/Cmd+B"})
	buildItem.Activate = f.buildProject
	buildMenu.Add(buildItem)
	runItem := forms.NewMenuItem("Run Project")
	runItem.Activate = f.runProject
	buildMenu.Add(runItem)
	f.menuBar.Add(buildMenu)
	viewMenu := forms.NewMenu("View")
	f.lightThemeItem = forms.NewMenuItem("Light Theme")
	f.lightThemeItem.SetChecked(true)
	f.lightThemeItem.Activate = f.useLightTheme
	viewMenu.Add(f.lightThemeItem)
	f.darkThemeItem = forms.NewMenuItem("Dark Theme")
	f.darkThemeItem.SetChecked(false)
	f.darkThemeItem.Activate = f.useDarkTheme
	viewMenu.Add(f.darkThemeItem)
	f.menuBar.Add(viewMenu)
	f.Form.SetMenuBar(f.menuBar)
	f.statusBar = forms.NewStatusBar()
	f.statusBar.SetAccessibilityID("main-status")
	f.statusBar.SetFont(uiFont)
	f.statusBar.SetText("Ready")
	f.statusBar.SetBounds(rect(0, 0, 320, 24))
	f.statusBar.SetDock(forms.DockBottom)
	f.editorFrame.ShowDesigner = f.showDesigner
	f.designer.ShowCode = f.showCode
	f.designer.SetDesign(&f.design)
	f.designer.Changed = f.designerChanged
	f.designer.SelectionChanged = f.designerSelectionChanged
	f.designer.AddControl = f.addDesignerControl
	f.designer.DeleteSelection = f.deleteDesignerControl
	f.inspector.SetDesign(&f.design)
	f.inspector.Changed = f.designerChanged
	f.inspector.CreateEvent = f.createDesignerEvent

	f.explorer = ide.NewExplorerControl(ide.OpenExplorer(root))
	f.explorer.SetAccessibilityID("project-explorer")
	f.explorer.SetFont(uiFont)
	f.explorer.OpenFile = f.explorerOpenFile

	f.editor = ide.NewEditorControl(ide.NewDocument(nil))
	f.editor.SetAccessibilityID("code-editor")
	f.editor.SetFont(codeFont)
	f.editor.Save = f.saveCurrentFile
	f.editor.Changed = f.editorChanged
	f.editor.Complete = f.completeEditor
	f.editor.Signature = f.signatureEditor

	f.Resize = f.formResize
	f.Add(&f.appBar.Control)
	f.Add(&f.explorerFrame.Control)
	f.Add(&f.editorFrame.Control)
	f.Add(&f.designer.Control)
	f.Add(&f.inspector.Control)
	f.Add(&f.output.Control)
	f.Add(&f.explorer.Control)
	f.Add(&f.editor.Control)
	f.Add(&f.targetMenu.Control)
	f.Add(&f.menuBar.Control)
	f.Add(&f.statusBar.Control)
	f.designer.SetVisible(false)
	f.inspector.SetVisible(false)
	f.targetMenu.SetVisible(false)
	f.setDarkTheme(false)
	f.formResize()
}

func rect(x, y, width, height int) graphics.Rect {
	return graphics.R(graphics.Scalar(x), graphics.Scalar(y), graphics.Scalar(width), graphics.Scalar(height))
}
