package main

import (
	renvoos "renvo.dev/std/os"
)

const projectMainFile = "main.go"
const projectUserFormFile = "main_form.go"
const projectGeneratedFormFile = "main_form_generated.go"
const projectModuleFile = "go.mod"
const projectOutputFile = "hello-app"

type formDesign struct {
	width        int
	height       int
	paintHandler string
	controls     []designerControl
}

type designerControl struct {
	kind         string
	name         string
	text         string
	x            int
	y            int
	width        int
	height       int
	checked      bool
	clickHandler string
	paintHandler string
}

const designerLabel = "label"
const designerButton = "button"
const designerTextBox = "textBox"
const designerTextArea = "textArea"
const designerCheckBox = "checkBox"
const designerRadioButton = "radioButton"
const designerPictureBox = "pictureBox"
const designerPanel = "panel"

type projectActionResult struct {
	message string
	ok      bool
}

func workspaceHasPrefix(value, prefix string) bool {
	if len(value) < len(prefix) {
		return false
	}
	for i := 0; i < len(prefix); i++ {
		if value[i] != prefix[i] {
			return false
		}
	}
	return true
}

func defaultFormDesign() formDesign {
	return formDesign{
		width:  420,
		height: 240,
		controls: []designerControl{
			{kind: designerLabel, name: "messageLabel", text: "Click the button to continue.", x: 50, y: 48, width: 320, height: 32},
			{kind: designerButton, name: "helloButton", text: "Say Hello", x: 50, y: 105, width: 320, height: 44, clickHandler: "helloButtonClick"},
		},
	}
}

// ensureHelloWorldProject gives an empty directory a complete first Forms
// application. Existing Go projects are never rewritten or supplemented.
func ensureHelloWorldProject(root string) (bool, string) {
	entries, err := renvoos.ReadDir(root)
	if err != nil {
		return false, "Could not read the project directory."
	}
	for i := 0; i < len(entries); i++ {
		name := entries[i].Name()
		if !entries[i].IsDir() && workspaceHasSuffix(name, ".go") {
			return false, ""
		}
	}
	design := defaultFormDesign()
	files := []string{projectModuleFile, projectMainFile, projectUserFormFile, projectGeneratedFormFile}
	data := [][]byte{[]byte("module example.com/hello\n\nrequire renvo.dev v0.0.0\n"), helloMainSource(), helloUserFormSource(), generatedFormSource(design)}
	for i := 0; i < len(files); i++ {
		if renvoos.WriteFile(workspaceJoinPath(root, files[i]), data[i], 0644) != nil {
			return false, "Could not create " + files[i] + "."
		}
	}
	return true, "Created a Hello World Forms project."
}

func helloMainSource() []byte {
	return []byte(`package main

import (
	"renvo.dev/forms"
	"renvo.dev/std/graphics"
)

func main() {
	window := graphics.NewWindow(graphics.WindowOptions{Title: "Hello World", Width: 420, Height: 240})
	if window == nil {
		return
	}
	form := NewMainForm()
	forms.NewApp(window, &form.Form).Run()
}
`)
}

func helloUserFormSource() []byte {
	return []byte(`package main

// User code belongs in this file. The designer never rewrites it.
func (f *MainForm) helloButtonClick() {
	f.messageLabel.SetText("Hello, World!")
}
`)
}

func generatedFormSource(design formDesign) []byte {
	out := make([]byte, 0, 1800+len(design.controls)*500)
	out = append(out, "// Code generated by RENVO Forms Designer; DO NOT EDIT.\n"...)
	out = append(out, "// The designer model is this Go source; there is no companion UI format.\n\n"...)
	out = append(out, "package main\n\n"...)
	out = append(out, "import (\n\t\"renvo.dev/forms\"\n\t\"renvo.dev/std/graphics\"\n\t\"renvo.dev/std/graphics/gofont\"\n)\n\n"...)
	out = append(out, "type MainForm struct {\n\tforms.Form\n\tuiFont *graphics.Font\n"...)
	for i := 0; i < len(design.controls); i++ {
		control := design.controls[i]
		out = append(out, '\t')
		out = append(out, control.name...)
		out = append(out, " *forms."...)
		out = append(out, designerFormsType(control.kind)...)
		out = append(out, '\n')
	}
	out = append(out, "}\n\n"...)
	out = append(out, "func NewMainForm() *MainForm {\n\tform := &MainForm{}\n\tform.initializeComponent()\n\treturn form\n}\n\n"...)
	out = append(out, "func (f *MainForm) initializeComponent() {\n"...)
	out = append(out, "\tf.Form.Initialize("...)
	out = append(out, workspaceDecimal(design.width)...)
	out = append(out, ", "...)
	out = append(out, workspaceDecimal(design.height)...)
	out = append(out, ")\n"...)
	out = append(out, "\tf.Form.SetBackground(graphics.RGBA(250, 251, 253, 255))\n\tf.uiFont = gofont.New(15)\n\n"...)
	if design.paintHandler != "" {
		out = append(out, "\tf.Form.PaintBackground = f."...)
		out = append(out, design.paintHandler...)
		out = append(out, "\n\n"...)
	}
	for i := 0; i < len(design.controls); i++ {
		control := design.controls[i]
		out = append(out, "\tf."...)
		out = append(out, control.name...)
		out = append(out, " = forms.New"...)
		out = append(out, designerFormsType(control.kind)...)
		out = append(out, "()\n"...)
		out = append(out, "\tf."...)
		out = append(out, control.name...)
		out = append(out, ".SetBounds(graphics.R("...)
		out = append(out, workspaceDecimal(control.x)...)
		out = append(out, ", "...)
		out = append(out, workspaceDecimal(control.y)...)
		out = append(out, ", "...)
		out = append(out, workspaceDecimal(control.width)...)
		out = append(out, ", "...)
		out = append(out, workspaceDecimal(control.height)...)
		out = append(out, "))\n"...)
		if designerControlHasFont(control.kind) {
			out = append(out, "\tf."...)
			out = append(out, control.name...)
			out = append(out, ".SetFont(f.uiFont)\n"...)
		}
		if control.kind == designerLabel {
			out = append(out, "\tf."...)
			out = append(out, control.name...)
			out = append(out, ".SetForeground(graphics.RGBA(32, 36, 42, 255))\n"...)
		}
		if designerControlHasText(control.kind) {
			out = append(out, "\tf."...)
			out = append(out, control.name...)
			out = append(out, ".SetText("...)
			out = appendGoQuoted(out, control.text)
			out = append(out, ")\n"...)
		}
		if designerControlHasChecked(control.kind) {
			out = append(out, "\tf."...)
			out = append(out, control.name...)
			if control.checked {
				out = append(out, ".SetChecked(true)\n"...)
			} else {
				out = append(out, ".SetChecked(false)\n"...)
			}
		}
		if control.kind == designerButton && control.clickHandler != "" {
			out = append(out, "\tf."...)
			out = append(out, control.name...)
			out = append(out, ".Click = f."...)
			out = append(out, control.clickHandler...)
			out = append(out, '\n')
		}
		if control.paintHandler != "" {
			out = append(out, "\tf."...)
			out = append(out, control.name...)
			out = append(out, ".Paint = f."...)
			out = append(out, control.paintHandler...)
			out = append(out, '\n')
		}
		out = append(out, '\n')
	}
	for i := 0; i < len(design.controls); i++ {
		out = append(out, "\tf.Form.Add(&f."...)
		out = append(out, design.controls[i].name...)
		out = append(out, ".Control)\n"...)
	}
	out = append(out, "}\n"...)
	return out
}

// parseFormDesign reads the deterministic Go emitted above. The Go file
// is the persisted designer document; selection and drag state are deliberately
// not encoded alongside the application source.
func parseFormDesign(source []byte) (formDesign, string) {
	design := defaultFormDesign()
	design.controls = nil
	lines := designerSourceLines(string(source))
	for i := 0; i < len(lines); i++ {
		line := designerTrimSpace(lines[i])
		if designerHasPrefix(line, "f.Form.Initialize(") {
			values, ok := designerCallInts(line, "f.Form.Initialize(", 2)
			if !ok || values[0] < 1 || values[1] < 1 {
				return design, "The generated form has an invalid client size."
			}
			design.width = values[0]
			design.height = values[1]
			continue
		}
		if designerHasPrefix(line, "f.Form.PaintBackground = f.") {
			design.paintHandler = line[len("f.Form.PaintBackground = f."):]
			continue
		}
		name, kind := designerConstructor(line)
		if name != "" {
			design.controls = append(design.controls, designerControl{kind: kind, name: name, width: 80, height: 28})
			continue
		}
		for j := 0; j < len(design.controls); j++ {
			control := &design.controls[j]
			prefix := "f." + control.name
			if designerHasPrefix(line, prefix+".SetBounds(") {
				values, ok := designerCallInts(line, prefix+".SetBounds(graphics.R(", 4)
				if !ok {
					return design, "The generated bounds for " + control.name + " could not be read."
				}
				control.x = values[0]
				control.y = values[1]
				control.width = values[2]
				control.height = values[3]
			} else if designerHasPrefix(line, prefix+".SetText(") {
				value, ok := designerQuotedArgument(line, prefix+".SetText(")
				if !ok {
					return design, "The generated text for " + control.name + " could not be read."
				}
				control.text = value
			} else if designerHasPrefix(line, prefix+".Click = f.") {
				control.clickHandler = line[len(prefix+".Click = f."):]
			} else if designerHasPrefix(line, prefix+".Paint = f.") {
				control.paintHandler = line[len(prefix+".Paint = f."):]
			} else if line == prefix+".SetChecked(true)" {
				control.checked = true
			} else if line == prefix+".SetChecked(false)" {
				control.checked = false
			}
		}
	}
	if len(design.controls) == 0 {
		return design, "No designer controls were found in " + projectGeneratedFormFile + "."
	}
	return design, ""
}

func designerFormsType(kind string) string {
	if kind == designerButton {
		return "Button"
	}
	if kind == designerTextBox {
		return "TextBox"
	}
	if kind == designerTextArea {
		return "TextArea"
	}
	if kind == designerCheckBox {
		return "CheckBox"
	}
	if kind == designerRadioButton {
		return "RadioButton"
	}
	if kind == designerPictureBox {
		return "PictureBox"
	}
	if kind == designerPanel {
		return "Panel"
	}
	return "Label"
}

func designerControlHasFont(kind string) bool {
	return kind != designerPictureBox && kind != designerPanel
}

func designerControlHasText(kind string) bool {
	return kind != designerPictureBox && kind != designerPanel
}

func designerControlHasChecked(kind string) bool {
	return kind == designerCheckBox || kind == designerRadioButton
}

func designerConstructor(line string) (string, string) {
	kinds := []string{designerLabel, designerButton, designerTextBox, designerTextArea, designerCheckBox, designerRadioButton, designerPictureBox, designerPanel}
	for i := 0; i < len(kinds); i++ {
		suffix := " = forms.New" + designerFormsType(kinds[i]) + "()"
		if name := designerConstructorName(line, suffix); name != "" {
			return name, kinds[i]
		}
	}
	return "", ""
}

func designerSourceLines(source string) []string {
	lines := make([]string, 0, 64)
	start := 0
	for i := 0; i < len(source); i++ {
		if source[i] == '\n' {
			lines = append(lines, source[start:i])
			start = i + 1
		}
	}
	if start < len(source) {
		lines = append(lines, source[start:])
	}
	return lines
}

func designerTrimSpace(value string) string {
	start := 0
	for start < len(value) && (value[start] == ' ' || value[start] == '\t' || value[start] == '\r') {
		start++
	}
	end := len(value)
	for end > start && (value[end-1] == ' ' || value[end-1] == '\t' || value[end-1] == '\r') {
		end--
	}
	return value[start:end]
}

func designerHasPrefix(value, prefix string) bool {
	if len(value) < len(prefix) {
		return false
	}
	return value[:len(prefix)] == prefix
}

func designerHasSuffix(value, suffix string) bool {
	if len(value) < len(suffix) {
		return false
	}
	return value[len(value)-len(suffix):] == suffix
}

func designerConstructorName(line, suffix string) string {
	if !designerHasPrefix(line, "f.") || !designerHasSuffix(line, suffix) {
		return ""
	}
	name := line[2 : len(line)-len(suffix)]
	if !designerIdentifier(name) {
		return ""
	}
	return name
}

func designerCallInts(line, prefix string, count int) ([]int, bool) {
	values := make([]int, 0, count)
	if !designerHasPrefix(line, prefix) {
		return values, false
	}
	i := len(prefix)
	for len(values) < count {
		for i < len(line) && (line[i] == ' ' || line[i] == ',') {
			i++
		}
		start := i
		if i < len(line) && line[i] == '-' {
			i++
		}
		for i < len(line) && line[i] >= '0' && line[i] <= '9' {
			i++
		}
		if start == i {
			return values, false
		}
		value, ok := designerParseInt(line[start:i])
		if !ok {
			return values, false
		}
		values = append(values, value)
	}
	return values, true
}

func designerParseInt(value string) (int, bool) {
	if value == "" {
		return 0, false
	}
	sign := 1
	i := 0
	if value[0] == '-' {
		sign = -1
		i = 1
	}
	if i == len(value) {
		return 0, false
	}
	result := 0
	for ; i < len(value); i++ {
		if value[i] < '0' || value[i] > '9' {
			return 0, false
		}
		result = result*10 + int(value[i]-'0')
	}
	return result * sign, true
}

func designerQuotedArgument(line, prefix string) (string, bool) {
	if !designerHasPrefix(line, prefix) || len(line) <= len(prefix) || line[len(prefix)] != '"' {
		return "", false
	}
	out := make([]byte, 0, len(line)-len(prefix))
	for i := len(prefix) + 1; i < len(line); i++ {
		if line[i] == '"' {
			return string(out), true
		}
		if line[i] == '\\' {
			i++
			if i >= len(line) {
				return "", false
			}
			if line[i] == 'n' {
				out = append(out, '\n')
			} else if line[i] == 'r' {
				out = append(out, '\r')
			} else if line[i] == 't' {
				out = append(out, '\t')
			} else {
				out = append(out, line[i])
			}
		} else {
			out = append(out, line[i])
		}
	}
	return "", false
}

func designerIdentifier(value string) bool {
	if value == "" || !designerIdentifierStart(value[0]) {
		return false
	}
	for i := 1; i < len(value); i++ {
		if !designerIdentifierStart(value[i]) && (value[i] < '0' || value[i] > '9') {
			return false
		}
	}
	return true
}

func designerIdentifierStart(value byte) bool {
	return value == '_' || value >= 'a' && value <= 'z' || value >= 'A' && value <= 'Z'
}

func appendGoQuoted(out []byte, value string) []byte {
	out = append(out, '"')
	for i := 0; i < len(value); i++ {
		c := value[i]
		if c == '\\' || c == '"' {
			out = append(out, '\\')
		}
		if c == '\n' {
			out = append(out, '\\', 'n')
		} else if c == '\r' {
			out = append(out, '\\', 'r')
		} else if c == '\t' {
			out = append(out, '\\', 't')
		} else {
			out = append(out, c)
		}
	}
	out = append(out, '"')
	return out
}

func workspaceJoinPath(root, name string) string {
	if root == "" || root == "." {
		return name
	}
	last := root[len(root)-1]
	if last == '/' || last == '\\' {
		return root + name
	}
	return root + "/" + name
}

func workspaceHasSuffix(value, suffix string) bool {
	if len(value) < len(suffix) {
		return false
	}
	start := len(value) - len(suffix)
	for i := 0; i < len(suffix); i++ {
		if value[start+i] != suffix[i] {
			return false
		}
	}
	return true
}
