package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type compatibility struct {
	SameVersion        string `json:"same_version"`
	NewOptionalTag     string `json:"new_optional_tag"`
	BreakingChange     string `json:"breaking_change"`
	UnsupportedVersion string `json:"unsupported_version"`
}

type field struct {
	Name     string `json:"name"`
	Encoding string `json:"encoding"`
}

type record struct {
	Name   string  `json:"name"`
	Fields []field `json:"fields"`
}

type tag struct {
	Name     string `json:"name"`
	Number   int    `json:"number"`
	Role     string `json:"role"`
	Required bool   `json:"required"`
	Payload  string `json:"payload"`
	Record   string `json:"record"`
}

type schema struct {
	Magic         string        `json:"magic"`
	Version       int           `json:"version"`
	ByteOrder     string        `json:"byte_order"`
	Header        string        `json:"header"`
	Compatibility compatibility `json:"compatibility"`
	Validation    []string      `json:"validation"`
	Tags          []tag         `json:"tags"`
	Records       []record      `json:"records"`
}

var schemaPath = flag.String("schema", "unit/schema.json", "schema definition")
var rootPath = flag.String("root", ".", "repository root")
var checkOnly = flag.Bool("check", false, "check generated files without writing")

func main() {
	flag.Parse()
	raw, err := os.ReadFile(*schemaPath)
	if err != nil {
		fatal(err)
	}
	var spec schema
	if err := json.Unmarshal(raw, &spec); err != nil {
		fatal(err)
	}
	if err := validate(spec); err != nil {
		fatal(err)
	}
	hash := sha256.Sum256(raw)
	digest := hex.EncodeToString(hash[:])
	outputs := map[string][]byte{
		"unit/schema_generated.go":             hostGo(spec, digest),
		"../internal/unit/schema_generated.go": internalGo(spec, digest),
		"compiler_unit_impl.go":                backendGo(spec, digest),
		"docs/unit-v1.md":                      documentation(spec, digest),
	}
	paths := make([]string, 0, len(outputs))
	for path := range outputs {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	for _, path := range paths {
		full := filepath.Join(*rootPath, path)
		want := outputs[path]
		if strings.HasSuffix(path, ".go") {
			want, err = format.Source(want)
			if err != nil {
				fatal(fmt.Errorf("format %s: %w", path, err))
			}
		}
		if *checkOnly {
			got, readErr := os.ReadFile(full)
			if readErr != nil || !bytes.Equal(got, want) {
				fatal(fmt.Errorf("generated file is stale: %s", path))
			}
			continue
		}
		if err := os.MkdirAll(filepath.Dir(full), 0755); err != nil {
			fatal(err)
		}
		if err := os.WriteFile(full, want, 0644); err != nil {
			fatal(err)
		}
	}
}

func validate(spec schema) error {
	if len(spec.Magic) != 4 || spec.Version < 1 || spec.ByteOrder == "" || spec.Header == "" || len(spec.Validation) == 0 {
		return fmt.Errorf("invalid header contract")
	}
	records := map[string]bool{}
	for _, rec := range spec.Records {
		if rec.Name == "" || records[rec.Name] || len(rec.Fields) == 0 {
			return fmt.Errorf("invalid or duplicate record %q", rec.Name)
		}
		records[rec.Name] = true
	}
	numbers := map[int]bool{}
	names := map[string]bool{}
	rootCount := 0
	childCount := 0
	for _, item := range spec.Tags {
		if item.Name == "" || item.Number < 1 || item.Number > 65535 || numbers[item.Number] || names[item.Name] {
			return fmt.Errorf("invalid or duplicate tag %q/%d", item.Name, item.Number)
		}
		numbers[item.Number] = true
		names[item.Name] = true
		if item.Role == "root" {
			rootCount++
		} else if item.Role != "child" {
			return fmt.Errorf("invalid role for tag %s", item.Name)
		} else {
			childCount++
		}
		if item.Record != "" && !records[item.Record] {
			return fmt.Errorf("tag %s references unknown record %s", item.Name, item.Record)
		}
	}
	if rootCount != 1 {
		return fmt.Errorf("schema has %d root tags", rootCount)
	}
	if childCount > 32 {
		return fmt.Errorf("schema has %d child tags; generated masks support 32", childCount)
	}
	return nil
}

func generatedHeader(digest string) string {
	return "// Code generated by renvoschemagen; DO NOT EDIT.\n// schema-sha256: " + digest + "\n\n"
}

func writeConstants(out *bytes.Buffer, spec schema, prefix string) {
	fmt.Fprintf(out, "const (\n\t%sMagic = %q\n\t%sVersion = %d\n", prefix, spec.Magic, prefix, spec.Version)
	for _, item := range spec.Tags {
		fmt.Fprintf(out, "\t%sTag%s = %d\n", prefix, item.Name, item.Number)
	}
	fmt.Fprintln(out, ")")
	writeTagHelpers(out, spec, prefix)
}

func writeTagHelpers(out *bytes.Buffer, spec schema, prefix string) {
	base := "schema"
	if prefix != "" {
		base = prefix
	}
	lowRequired := 0
	highRequired := 0
	children := make([]tag, 0, len(spec.Tags))
	for _, item := range spec.Tags {
		if item.Role != "child" {
			continue
		}
		childIndex := len(children)
		children = append(children, item)
		if item.Required {
			if childIndex < 16 {
				lowRequired |= 1 << childIndex
			} else {
				highRequired |= 1 << (childIndex - 16)
			}
		}
	}
	fmt.Fprintf(out, "\nfunc %sChildTagIndex(tag int) int {\n", base)
	for start := 0; start < len(children); {
		end := start + 1
		for end < len(children) && children[end].Number == children[end-1].Number+1 {
			end++
		}
		first := children[start]
		if end-start == 1 {
			fmt.Fprintf(out, "\tif tag == %sTag%s {\n\t\treturn %d\n\t}\n", prefix, first.Name, start)
		} else {
			last := children[end-1]
			fmt.Fprintf(out, "\tif tag >= %sTag%s && tag <= %sTag%s {\n\t\treturn tag - %d\n\t}\n", prefix, first.Name, prefix, last.Name, first.Number-start)
		}
		start = end
	}
	fmt.Fprintln(out, "\treturn -1\n}")
	fmt.Fprintf(out, "\nconst %sRequiredChildMaskLow = %d\n", base, lowRequired)
	fmt.Fprintf(out, "const %sRequiredChildMaskHigh = %d\n", base, highRequired)
}

func hostGo(spec schema, digest string) []byte {
	var out bytes.Buffer
	out.WriteString(generatedHeader(digest))
	out.WriteString("package unit\n\n")
	writeConstants(&out, spec, "")
	out.WriteString(`
type SchemaTag struct {
	Name string
	Number uint16
	Role string
	Required bool
	Payload string
	Record string
}

type SchemaField struct {
	Name string
	Encoding string
}

type SchemaRecord struct {
	Name string
	Fields []SchemaField
}

`)
	fmt.Fprintln(&out, "var WireSchemaTags = []SchemaTag{")
	for _, item := range spec.Tags {
		fmt.Fprintf(&out, "\t{%q, %d, %q, %t, %q, %q},\n", item.Name, item.Number, item.Role, item.Required, item.Payload, item.Record)
	}
	fmt.Fprintln(&out, "}")
	fmt.Fprintln(&out, "var WireSchemaRecords = []SchemaRecord{")
	for _, rec := range spec.Records {
		fmt.Fprintf(&out, "\t{Name: %q, Fields: []SchemaField{\n", rec.Name)
		for _, field := range rec.Fields {
			fmt.Fprintf(&out, "\t\t{%q, %q},\n", field.Name, field.Encoding)
		}
		fmt.Fprintln(&out, "\t}},")
	}
	fmt.Fprintln(&out, "}")
	return out.Bytes()
}

func internalGo(spec schema, digest string) []byte {
	var out bytes.Buffer
	out.WriteString(generatedHeader(digest))
	out.WriteString("package unit\n\n")
	writeConstants(&out, spec, "")
	return out.Bytes()
}

func backendGo(spec schema, digest string) []byte {
	var out bytes.Buffer
	out.WriteString(generatedHeader(digest))
	out.WriteString("package main\n\n")
	writeConstants(&out, spec, "renvoUnit")
	return out.Bytes()
}

func documentation(spec schema, digest string) []byte {
	var out bytes.Buffer
	fmt.Fprintf(&out, "<!-- Code generated by renvoschemagen from unit/schema.json. -->\n<!-- schema-sha256: %s -->\n\n", digest)
	fmt.Fprintf(&out, "# Renvo unit version %d format\n\n", spec.Version)
	fmt.Fprintf(&out, "A Renvo unit is a length-delimited compiler handoff. The authoritative machine-readable definition is `backend/unit/schema.json`. All fixed-width values use %s order.\n\n", spec.ByteOrder)
	fmt.Fprintf(&out, "Header: `%s`. The root payload must consume the remainder of the file exactly. Each child is `tag:u16, length:u32, payload[length]`.\n\n", spec.Header)
	out.WriteString("Unsigned integers inside record payloads use base-128 uvarints. Nullable integers encode `value+1`, reserving zero for absent. Signed integers use zigzag encoding. Every counted table begins with its record count and must contain no trailing payload bytes.\n\n")
	out.WriteString("## Tags\n\n| Tag | Name | Required | Payload | Record |\n| ---: | --- | --- | --- | --- |\n")
	for _, item := range spec.Tags {
		required := "no"
		if item.Required {
			required = "yes"
		}
		fmt.Fprintf(&out, "| %d | %s | %s | %s | %s |\n", item.Number, item.Name, required, item.Payload, item.Record)
	}
	out.WriteString("\nAll known child tags are singletons. Readers reject duplicate known tags and missing required tags. Unknown child tags are skipped by length.\n\n## Records\n")
	for _, rec := range spec.Records {
		fmt.Fprintf(&out, "\n### %s\n\n| Field | Encoding |\n| --- | --- |\n", rec.Name)
		for _, field := range rec.Fields {
			fmt.Fprintf(&out, "| %s | %s |\n", field.Name, field.Encoding)
		}
	}
	out.WriteString("\n## Validation\n\n")
	for _, rule := range spec.Validation {
		fmt.Fprintf(&out, "- %s\n", rule)
	}
	out.WriteString("\n## Compatibility\n\n")
	fmt.Fprintf(&out, "- Same version: %s\n", spec.Compatibility.SameVersion)
	fmt.Fprintf(&out, "- New optional tags: %s\n", spec.Compatibility.NewOptionalTag)
	fmt.Fprintf(&out, "- Breaking changes: %s\n", spec.Compatibility.BreakingChange)
	fmt.Fprintf(&out, "- Unsupported versions: %s\n", spec.Compatibility.UnsupportedVersion)
	return out.Bytes()
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "renvoschemagen:", err)
	os.Exit(1)
}
