package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
)

type protocol struct {
	Name      string      `json:"name"`
	Version   uint16      `json:"version"`
	ByteOrder string      `json:"byte_order"`
	Magic     string      `json:"magic"`
	Size      uint16      `json:"size"`
	Symbol    string      `json:"symbol"`
	Section   string      `json:"section"`
	Fields    []fieldSpec `json:"fields"`
	States    []stateSpec `json:"states"`
}

type fieldSpec struct {
	Name   string `json:"name"`
	Offset int    `json:"offset"`
	Size   int    `json:"size"`
}

type stateSpec struct {
	Name  string `json:"name"`
	Value uint32 `json:"value"`
}

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, "rtgresultgen:", err)
		os.Exit(1)
	}
}

func run(args []string) error {
	flags := flag.NewFlagSet("rtgresultgen", flag.ContinueOnError)
	specPath := flags.String("spec", "protocol.json", "protocol specification")
	goPath := flags.String("go", "layout_generated.go", "generated Go output")
	cPath := flags.String("c", "result_abi.h", "generated C89 header")
	check := flags.Bool("check", false, "verify outputs without changing them")
	if err := flags.Parse(args); err != nil {
		return err
	}
	spec, err := loadProtocol(*specPath)
	if err != nil {
		return err
	}
	goData, err := generateGo(spec)
	if err != nil {
		return err
	}
	cData := generateC(spec)
	for _, output := range []struct {
		path string
		data []byte
	}{{*goPath, goData}, {*cPath, cData}} {
		if *check {
			current, readErr := os.ReadFile(output.path)
			if readErr != nil {
				return readErr
			}
			if !bytes.Equal(current, output.data) {
				return fmt.Errorf("%s is stale", output.path)
			}
			continue
		}
		if err := os.MkdirAll(filepath.Dir(output.path), 0o755); err != nil && filepath.Dir(output.path) != "." {
			return err
		}
		if err := os.WriteFile(output.path, output.data, 0o644); err != nil {
			return err
		}
	}
	return nil
}

func loadProtocol(path string) (protocol, error) {
	var spec protocol
	data, err := os.ReadFile(path)
	if err != nil {
		return spec, err
	}
	if err := json.Unmarshal(data, &spec); err != nil {
		return spec, err
	}
	if spec.ByteOrder != "little" {
		return spec, errors.New("byte_order must be little")
	}
	if len(spec.Magic) != 4 || spec.Size == 0 || spec.Symbol == "" || spec.Section == "" {
		return spec, errors.New("magic, size, symbol, and section are required")
	}
	occupied := make([]bool, int(spec.Size))
	for _, field := range spec.Fields {
		if field.Name == "" || field.Offset < 0 || field.Size <= 0 || field.Offset+field.Size > int(spec.Size) {
			return spec, fmt.Errorf("invalid field %+v", field)
		}
		for i := field.Offset; i < field.Offset+field.Size; i++ {
			if occupied[i] {
				return spec, fmt.Errorf("field %s overlaps byte %d", field.Name, i)
			}
			occupied[i] = true
		}
	}
	return spec, nil
}

func generateGo(spec protocol) ([]byte, error) {
	var out bytes.Buffer
	fmt.Fprintln(&out, "// Code generated by rtgresultgen from protocol.json. DO NOT EDIT.")
	fmt.Fprintln(&out, "package resultabi")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "type State uint32")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "const (")
	fmt.Fprintf(&out, "\tMagic uint32 = %#x\n", magicValue(spec.Magic))
	fmt.Fprintf(&out, "\tVersion uint16 = %d\n", spec.Version)
	fmt.Fprintf(&out, "\tSize = %d\n", spec.Size)
	fmt.Fprintf(&out, "\tSymbolName = %q\n", spec.Symbol)
	fmt.Fprintf(&out, "\tSectionName = %q\n", spec.Section)
	for _, field := range spec.Fields {
		fmt.Fprintf(&out, "\tOffset%s = %d\n", goName(field.Name), field.Offset)
		fmt.Fprintf(&out, "\tFieldSize%s = %d\n", goName(field.Name), field.Size)
	}
	fmt.Fprintln(&out, ")")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "const (")
	for _, state := range spec.States {
		fmt.Fprintf(&out, "\tState%s State = %d\n", goName(state.Name), state.Value)
	}
	fmt.Fprintln(&out, ")")
	return format.Source(out.Bytes())
}

func generateC(spec protocol) []byte {
	var out bytes.Buffer
	fmt.Fprintln(&out, "/* Code generated by rtgresultgen from protocol.json. DO NOT EDIT. */")
	fmt.Fprintln(&out, "#ifndef RTG_RESULT_ABI_H")
	fmt.Fprintln(&out, "#define RTG_RESULT_ABI_H")
	fmt.Fprintln(&out, "#include <limits.h>")
	fmt.Fprintln(&out, "typedef char rtg_result_requires_8_bit_bytes[(CHAR_BIT == 8) ? 1 : -1];")
	fmt.Fprintln(&out, "typedef char rtg_result_requires_32_bit_ulong[(ULONG_MAX >= 4294967295UL) ? 1 : -1];")
	fmt.Fprintf(&out, "#define RTG_RESULT_MAGIC 0x%08xUL\n", magicValue(spec.Magic))
	fmt.Fprintf(&out, "#define RTG_RESULT_VERSION %dU\n", spec.Version)
	fmt.Fprintf(&out, "#define RTG_RESULT_SIZE %dU\n", spec.Size)
	fmt.Fprintln(&out, "#define RTG_RESULT_BYTE_ORDER_LITTLE 1")
	fmt.Fprintf(&out, "#define RTG_RESULT_SYMBOL %s\n", spec.Symbol)
	fmt.Fprintf(&out, "#define RTG_RESULT_SECTION \"%s\"\n", spec.Section)
	for _, field := range spec.Fields {
		fmt.Fprintf(&out, "#define RTG_RESULT_OFFSET_%s %dU\n", cName(field.Name), field.Offset)
		fmt.Fprintf(&out, "#define RTG_RESULT_FIELD_SIZE_%s %dU\n", cName(field.Name), field.Size)
	}
	for _, state := range spec.States {
		fmt.Fprintf(&out, "#define RTG_RESULT_STATE_%s %dUL\n", cName(state.Name), state.Value)
	}
	fmt.Fprintf(&out, "extern unsigned char %s[RTG_RESULT_SIZE];\n", spec.Symbol)
	fmt.Fprintln(&out, "#endif")
	return out.Bytes()
}

func magicValue(magic string) uint32 {
	return uint32(magic[0]) | uint32(magic[1])<<8 | uint32(magic[2])<<16 | uint32(magic[3])<<24
}

func goName(name string) string {
	var result strings.Builder
	for _, part := range strings.Split(name, "_") {
		if part == "" {
			continue
		}
		result.WriteString(strings.ToUpper(part[:1]))
		result.WriteString(part[1:])
	}
	return result.String()
}

func cName(name string) string {
	return strings.ToUpper(name)
}
